README.md
=> Adding blog post

.travlis.yml
We are using github actions for CI. cc #34
=> Remove travis yaml.

src/dispatch/conversation/models.py
We weren't correctly modeling our sqlalchemy model, and were dropping values that need to be set.
=> Fixing conversations pydantic model

docs/installation.md
This should not conflict with #42.
=> Fix one more documentation typo

docker/docker-entrypoint.sh
Address https://github.com/Netflix/dispatch/issues/43
=> Fix startup script syntax issues

docker/Dockerfile, docker/docker-entrypoint.sh
=> fix: add app argument for dispatch start in entrypoint

MANIFEST.in
Created MANIFEST.in in order to include additional files that are missing after building docker image. This may be too inclusive though since I just added everything in the `src/dispatch` folder, so adjust as necessary. Not familiar enough with the code to know what can or cannot be excluded.
This should resolve #59 and #60
=> Create MANIFEST to resolve missing files

.github/workflows/list_and_test.yml
=> Revert "Changes Docker Postgres username"

.github/workflows/list_and_test.yml, src/dispatch/database.py, src/dispatch/group/models.py, src/dispatch/incident/flows.py, src/dispatch/incident/messaging.py, src/dispatch/incident/service.py, src/dispatch/participant/flows.py, src/dispatch/participant/models.py, src/dispatch/participant/service.py, src/dispatch/participant_role/flows.py, src/dispatch/participant_role/models.py, src/dispatch/participant_role/service.py, src/dispatch/plugins/dispatch_slack/views.py, tests/conftest.py, tests/conversation/test_conversation_service.py, tests/factories.py, tests/group/test_group_service.py, tests/incident_priority/test_incident_priority_service.py, tests/incident_type/test_incident_type_service.py, tests/individual/test_individual_service.py, tests/participant/test_participant_service.py, tests/participant_role/test_participant_role_service.py, tests/service/test_service_service.py, tests/ticket/test_ticket_service.py
- Adds tests for participant and participant role service modules
- Migrates to SQLAlchemy scoped session
- Fixes pydantic model for Group
- Refactors incident service create function and some functions called in incident flows
=> Tests, refactoring, and bugfixes

src/dispatch/incident/flows.py, src/dispatch/incident/service.py, src/dispatch/participant/service.py, src/dispatch/participant_role/flows.py, src/dispatch/participant_role/service.py, tests/factories.py, tests/participant_role/test_participant_role_service.py
- Moves `add_participant_role()` function from the participant service module to the participant role service module as `add_role()` and improves it
- Adds test for the `add_role()` function
- Refactors the `create()` function in the incident service module
- Refactors the assign role flows to enable better role handling
=> Improves participant role flows

src/dispatch/cli.py
just one line change to simplify the python code
=> simplify the python code

src/dispatch/plugins/dispatch_google/groups/plugin.py
* Retrying an all HTTP error codes instead of maintaining a list of error codes we want to retry on.
=> Retries on all HTTP error codes

docker/.env.example, tests/conftest.py
Better to remove it now and add it back later when it's actually used for something
=> Remove unused DISPATCH_DOMAIN

.github/workflows/list_and_test.yml
Commenting samuelmeuli/lint-action logic until it supports forks. (see https://github.com/samuelmeuli/lint-action/issues/13)
=> Comments samuelmeuli/lint-action logic

src/dispatch/database.py
Fixes an issue where complex columns (i.e. relationship based columns) are now sortable. This was mostly affecting incident_type and incident_priority. But the fix should be in place across the app.
Hybrid column sorting and filtering will be addressed in #124
=> Relationship columns now sortable/filterable.

src/dispatch/incident/scheduled.py
This import seemed to be misspelled.
=> fixed a wrong import must be a typo

src/dispatch/static/dispatch/src/incident_type/store.js
This fixes an issue where the `Visibility` field in the New/ Edit form was not getting rendered properly.
=> Adds visibility field to incident type store.js

docs/configuration/plugins/google.md, docs/configuration/plugins/jira.md, docs/configuration/plugins/slack.md
* Fix google config doc to be consistent with var names in code.
* Fix jira config doc to signal sensitive var in password.
* Fix slack config doc to point to correct update incident endpoint.
=> Doc fixes.

src/dispatch/config.py
Adds the ability to encrypt environment secrets with KMS, similar to metatron.  Application would be responsible for setting `AWS_DEFAULT_REGION` environment variable.
=> Add KMS ability for Secret protection in env

.gitignore, data/dispatch-sample-data.dump, dispatch-data-only.dump, src/dispatch/cli.py
Add initial commit with a data-only dump of demo dispatch
=> [WIP] Add a data-only dump to the tree for feedback

README.md, docs/configuration/app.md, docs/configuration/plugins/configuring-g-suite.md, docs/configuration/plugins/configuring-zoom.md
- Adds documentation for Zoom plugin
- Updates G-Suite Docs to list the Calendar scope for Meet
- Adds link to README for Docs
- Updates App level config Doc to state Sentry DSN and Database Credentials are Secret
=> Add Zoom conference documentation and slight updates to other docs

src/dispatch/incident/scheduled.py, src/dispatch/plugins/dispatch_slack/views.py
=> Adds get involved button to daily summary emails. 

src/dispatch/plugins/dispatch_slack/views.py
Let's send the message when not in business hours.
=> Fixes Slack after hours message

src/dispatch/auth/service.py
=> Allows user auth to be disabled returning a default user.

src/dispatch/static/dispatch/src/router/config.js
=> Fixes incident types and priorities paths in the Web UI router config

src/dispatch/cli.py
Fixes the `server routes` command.
=> Importing main instead of api directly

src/dispatch/extensions.py, src/dispatch/main.py
=> Adds all plugin event API routes to the API router before adding this one to the Web API framework

docker/.dockerignore, src/dispatch/cli.py
Backporting hotfix to develop.
=> Fixing an issue with database being in a bad state (#268)

src/dispatch/plugin/service.py
This PR fixes an issue where required plugins couldn't be disabled even if another one of the same type was enabled.
=> Let's allow users to disable required plugins

src/dispatch/static/dispatch/package-lock.json, src/dispatch/static/dispatch/package.json, src/dispatch/static/dispatch/src/router/index.js
Remove nprogress bar, individual components have their own loading indicators.
=> Removing loading overlay

src/dispatch/auth/views.py, src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/router/index.js
In some auth flows (server side) only the server knows who is currently authenticated, for these flows we ask the server about the current user (via the `/me`) endpoint and set the data in the frontend accordingly.
=> Fetching current user info from server

docker/Dockerfile
* Changes keyserver used to fetch public keys
* Replaces gnupg with gnupg2
* Bumps GOSU_VERSION
=> Improves Dockerfile

.editorconfig, src/dispatch/conference/service.py, tests/conference/test_conference_service.py, tests/conftest.py, tests/factories.py
=> Adding Conference tests.

requirements-metrics.txt, src/dispatch/config.py, src/dispatch/incident/metrics.py
Switching to statsmodels for an easier install:  
https://www.statsmodels.org/stable/install.html  
Exponential smoothing info:  
https://www.statsmodels.org/stable/generated/statsmodels.tsa.holtwinters.ExponentialSmoothing.html#statsmodels.tsa.holtwinters.ExponentialSmoothing  
Using pandas data_range and reset_index to fill any missing months with 0:   
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html
=> changing from prophet to statsmodels

src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/views.py
Fixes incident reported confirmation message and applies Black formatting.
cc @vagharsh
=> Fixes incident reported confirmation message

src/dispatch/incident/metrics.py
=> Failing gracefully if there is insufficient data.

src/dispatch/incident/views.py, src/dispatch/static/dispatch/src/incident/Status.vue, src/dispatch/static/dispatch/src/incident/api.js, src/dispatch/static/dispatch/src/incident/store.js
=> Adds as join incident button to the incident status page

src/dispatch/static/dispatch/src/definition/Table.vue, src/dispatch/static/dispatch/src/document/Table.vue, src/dispatch/static/dispatch/src/incident/Table.vue, src/dispatch/static/dispatch/src/incident_priority/Table.vue, src/dispatch/static/dispatch/src/incident_type/Table.vue, src/dispatch/static/dispatch/src/individual/Table.vue, src/dispatch/static/dispatch/src/plugin/Table.vue, src/dispatch/static/dispatch/src/service/Table.vue, src/dispatch/static/dispatch/src/tag/Table.vue, src/dispatch/static/dispatch/src/team/Table.vue, src/dispatch/static/dispatch/src/term/Table.vue
=> Ensures all table actions are under row ellipsis menu

docker/Dockerfile
=> backslash is missing so build fails

src/dispatch/__init__.py
* Allows for building of static content during building, fixes #399
=> Allows for building of static content during building, fixes #399 (#345)

docker/Dockerfile
Closes https://github.com/Netflix/dispatch-docker/issues/53
=> Let's try several keyservers to ensure we have all the keys we need

setup.py, src/dispatch/config.py, src/dispatch/incident/service.py, src/dispatch/individual/service.py, src/dispatch/participant/service.py, src/dispatch/plugin/views.py, src/dispatch/plugins/dispatch_core/plugin.py, src/dispatch/plugins/dispatch_opsgenie/config.py, src/dispatch/plugins/dispatch_opsgenie/plugin.py, src/dispatch/plugins/dispatch_opsgenie/service.py, src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/service/service.py, src/dispatch/service/views.py, src/dispatch/static/dispatch/src/plugin/api.js, src/dispatch/static/dispatch/src/service/NewEditSheet.vue, src/dispatch/static/dispatch/src/service/store.js
Hello this PR tries to resolve some of the "tightly-coupled components" issue. 
- Contact plugin 
Removes the need for slack integration for ContactPlugin, and uses dispatch itself to resolve a individual
- Opsgenie plugin 
Second oncall plugin 
Opinions welcomed:
- If individual is not found (fetched from oncall-plugin) should it be created within dispatch, for further use?
- Should I include in this PR google hangouts, and google meet to get rid of slack necessity, leveraging a much easier dispatch installation as you would only have to configure and integrate it with google.
@kevgliss what do you think?
=> Decoupling some components 

src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/service.py
=> Cast slack 'secret' objects to strings explicitly

src/dispatch/static/dispatch/src/incident/IncidentPrimaryLocationBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentPrimaryTeamBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentPriorityBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentTypeBarChartCard.vue
Fixing an issue where missing values were not being reported as zero causing ragged arrays
=> Ragged data arrays

src/dispatch/static/dispatch/src/incident/IncidentCombobox.vue, src/dispatch/static/dispatch/src/task/Table.vue, src/dispatch/static/dispatch/src/task/TableFilterDialog.vue, src/dispatch/static/dispatch/src/task/store.js, src/dispatch/task/views.py
=> Adds the ability to filter tasks by associated incidents.

src/dispatch/messaging.py, src/dispatch/plugins/dispatch_google/gmail/plugin.py, src/dispatch/plugins/dispatch_google/gmail/templates/base.html, src/dispatch/plugins/dispatch_google/gmail/templates/executive_report.html, src/dispatch/report/flows.py, src/dispatch/report/messaging.py
This PR adds a new email template for executive report updates and support for sending the reports to the incident notifications group.
=> Adds support for emailing the executive report to the notifications group

src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/report/messaging.py
* Fixes reminder settings mapping
* Adds executive report to Slack template map
=> Executive report bugfixes (#410)

src/dispatch/static/dispatch/src/incident_priority/IncidentPrioritySelect.vue, src/dispatch/static/dispatch/src/incident_type/IncidentTypeSelect.vue
=> Adds descriptions to dropdowns

src/dispatch/static/dispatch/src/api.js
Fixes misspelling of `received` in src/dispatch/static/dispatch/src/api.js
=> Fix misspelling of `received`

docs/configuration/app.md
https://github.com/Netflix/dispatch/issues/360
https://github.com/Netflix/dispatch/issues/406
=> Mention that the basic auth plugins, requires DISPATCH_JWT_TOKEN

docs/configuration/plugins/configuring-g-suite.md, docs/configuration/plugins/configuring-slack.md
Fixing google permissions and slack command doc - recreated PR @mvilanova
=> Fixing google permissions and slack command doc

src/dispatch/plugins/dispatch_google/groups/plugin.py, src/dispatch/plugins/dispatch_slack/actions.py, src/dispatch/plugins/dispatch_slack/commands.py, src/dispatch/plugins/dispatch_slack/config.py, src/dispatch/plugins/dispatch_slack/dialogs.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/modals.py
=> Adds Slack command to update the notifications group

src/dispatch/plugins/dispatch_slack/dialogs.py
=> Adds hint to executive report dialog

src/dispatch/incident/messaging.py, src/dispatch/incident/scheduled.py, src/dispatch/messaging.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/plugin.py
Reminds every week on Monday, I chose not to make this configurable at this time.
=> Adding reminder for incidents that have been stable for over a week.

src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue, src/dispatch/static/dispatch/src/incident/IncidentTopTagsDonut.vue, src/dispatch/static/dispatch/src/incident/IncidentTopTermsDonut.vue
=> Adding common tags and terms donut graphs.

src/dispatch/cli.py, src/dispatch/common/utils/cli.py, src/dispatch/plugins/base/manager.py
=> Separates plugin install from startup.

src/dispatch/document/scheduled.py, src/dispatch/plugins/dispatch_google/gmail/plugin.py
=> Adding missing instance ref

src/dispatch/extensions.py
Add AioHttpIntegration and SqlalchemyIntegration to Sentry
=> Add AioHttpIntegration and SqlalchemyIntegration to Sentry

src/dispatch/incident_type/models.py, src/dispatch/static/dispatch/src/document/DocumentSelect.vue, src/dispatch/static/dispatch/src/incident_type/Table.vue, src/dispatch/static/dispatch/src/incident_type/store.js, tests/incident_type/test_incident_type_service.py
=> Adding missing validation.

src/dispatch/extensions.py
=> Fixing integration imports

requirements-base.txt
Changes causing the issue were reverted (https://github.com/tiangolo/fastapi/pull/1864#issuecomment-683283704).
=> Unpins fastapi

src/dispatch/incident/scheduled.py
Avoids errors when an incident does not have an incident document.
=> Incident documents are not a given

src/dispatch/config.py, src/dispatch/service/service.py
=> Removing unused references

src/dispatch/incident/service.py, src/dispatch/plugins/dispatch_slack/events.py, src/dispatch/tag/service.py
We should rely on the other values in the tag to determine if it's a duplicate tag.
=> External tags may not have an ID.

src/dispatch/common/utils/cli.py
=> Adding key errors as warnings

src/dispatch/incident/flows.py, src/dispatch/incident_type/models.py, src/dispatch/static/dispatch/src/document/DocumentSelect.vue
This makes defining an incident document optional for incident types.
=> Making document templates optional

src/dispatch/incident/flows.py, src/dispatch/incident/views.py, src/dispatch/static/dispatch/src/incident/ReportForm.vue, src/dispatch/static/dispatch/src/incident/store.js
Allows the incident to be created in a "closed" state, only creating a ticket if enabled and not running the rest of the create flow.
=> Allows for incidents to be created in 'Closed' state.

src/dispatch/incident/flows.py, src/dispatch/incident/messaging.py, src/dispatch/messaging.py, src/dispatch/participant_role/flows.py
Adds db_session for dispatch contact plugin, makes messaging more robust when missing data. Fixes #607
=> Adds missing db_session.

requirements-base.txt
Installs sentry sdk with flask to solve the issue described [here](https://github.com/getsentry/sentry-docs/issues/371). Also, removes a duplicate.
=> Updates Python requirements

src/dispatch/static/dispatch/src/api.js, src/dispatch/static/dispatch/src/auth/Login.vue, src/dispatch/static/dispatch/src/auth/Register.vue, src/dispatch/static/dispatch/src/auth/store.js
Ensures that our JWT survives page refresh. Also additions additional validation on the register/login forms.
=> Fixes issue where login is not persisted between page refresh

src/dispatch/auth/views.py, src/dispatch/database.py, src/dispatch/document/views.py, src/dispatch/feedback/views.py, src/dispatch/incident/models.py, src/dispatch/incident/views.py, src/dispatch/incident_priority/views.py, src/dispatch/incident_type/views.py, src/dispatch/individual/views.py, src/dispatch/participant/models.py, src/dispatch/plugin/views.py, src/dispatch/service/views.py, src/dispatch/static/dispatch/src/incident/Table.vue, src/dispatch/static/dispatch/src/tag/Table.vue, src/dispatch/static/dispatch/src/task/Table.vue, src/dispatch/tag/views.py, src/dispatch/tag_type/views.py, src/dispatch/task/models.py, src/dispatch/task/views.py, src/dispatch/team/views.py, src/dispatch/term/views.py, src/dispatch/workflow/views.py
Enables/Fixes filtering on:
- Tag Table -> Tag Type
- Task Table -> Creator, Owner, Due By, Incident Name, Incident Priority, Incident Type
=> Fixes filtering on several columns

src/dispatch/auth/models.py, src/dispatch/auth/views.py, src/dispatch/database.py, src/dispatch/enums.py, src/dispatch/incident/models.py, src/dispatch/incident/views.py, src/dispatch/search/views.py
Forces an 'and' clause for the /incidents endpoint when a non-admin user makes a request.
=> Fixes restricted incident filtering.

src/dispatch/route/service.py
Fixing an issue where context was optional in the model but not in the actual code.
=> Context Optional

src/dispatch/database.py
When we run a search we typically sort the results by their weighted relevance weights. When other sorts are applied (e.g. date) this can cause confusing results as it's sorted by both the weight and the date. From the end user perspective, it's clearer to simply drop the weighted sort and rely on the defined sort.
=> Fixing an issue with weighted search sort.

src/dispatch/plugin/service.py, src/dispatch/plugin/views.py, src/dispatch/service/service.py, src/dispatch/service/views.py, src/dispatch/static/dispatch/src/service/Table.vue
=> Oncall plugin-related UI warnings and improvements

src/dispatch/static/dispatch/src/app/store.js, src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/components/Snackbar.vue, src/dispatch/static/dispatch/src/definition/store.js, src/dispatch/static/dispatch/src/document/store.js, src/dispatch/static/dispatch/src/feedback/store.js, src/dispatch/static/dispatch/src/incident/store.js, src/dispatch/static/dispatch/src/incident_priority/store.js, src/dispatch/static/dispatch/src/incident_type/store.js, src/dispatch/static/dispatch/src/individual/store.js, src/dispatch/static/dispatch/src/plugin/store.js, src/dispatch/static/dispatch/src/service/store.js, src/dispatch/static/dispatch/src/tag/store.js, src/dispatch/static/dispatch/src/tag_type/store.js, src/dispatch/static/dispatch/src/task/store.js, src/dispatch/static/dispatch/src/team/store.js, src/dispatch/static/dispatch/src/term/store.js, src/dispatch/static/dispatch/src/workflow/store.js
=> UI errors are visible until closed

src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
=> Fixing issue exporting fields with null values

src/dispatch/static/dispatch/src/incident/IncidentSelect.vue
=> Fixes issue where other field matches are not displayed in dropdown

src/dispatch/static/dispatch/src/document/DocumentSelect.vue, src/dispatch/static/dispatch/src/incident/IncidentSelect.vue, src/dispatch/static/dispatch/src/service/ServiceSelect.vue, src/dispatch/static/dispatch/src/task/AssigneeCombobox.vue, src/dispatch/static/dispatch/src/task/OwnerSelect.vue
Let the server handling searching/filtering for these components.
=> Forcing server-side filtering

src/dispatch/static/dispatch/src/incident/Table.vue
=> Fixes incident table buttons

src/dispatch/report/flows.py, src/dispatch/report/messaging.py
This PR adds support for emailing tactical reports to the incident tactical group.
=> Emails the tactical report to the incident tactical group

src/dispatch/messaging/email/templates/executive_report.mjml, src/dispatch/messaging/email/templates/feedback_notification.mjml, src/dispatch/messaging/email/templates/tactical_report.mjml
=> Improves tactical, executive, and feedback email templates

src/dispatch/static/dispatch/src/task/store.js, src/dispatch/static/dispatch/src/team/store.js, src/dispatch/static/dispatch/src/workflow/store.js
=> Set loading to false for errors

src/dispatch/static/dispatch/src/api.js, src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/components/AppDrawer.vue, src/dispatch/static/dispatch/src/components/NotificationSnackbarsWrapper.vue, src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue, src/dispatch/static/dispatch/src/dashboard/TaskOverview.vue, src/dispatch/static/dispatch/src/definition/store.js, src/dispatch/static/dispatch/src/document/store.js, src/dispatch/static/dispatch/src/feedback/store.js, src/dispatch/static/dispatch/src/incident/store.js, src/dispatch/static/dispatch/src/incident_priority/store.js, src/dispatch/static/dispatch/src/incident_type/store.js, src/dispatch/static/dispatch/src/individual/store.js, src/dispatch/static/dispatch/src/notification/DeleteDialog.vue, src/dispatch/static/dispatch/src/notification/NewEditSheet.vue, src/dispatch/static/dispatch/src/notification/Table.vue, src/dispatch/static/dispatch/src/notification/api.js, src/dispatch/static/dispatch/src/notification/store.js, src/dispatch/static/dispatch/src/plugin/store.js, src/dispatch/static/dispatch/src/router/config.js, src/dispatch/static/dispatch/src/search/store.js, src/dispatch/static/dispatch/src/service/store.js, src/dispatch/static/dispatch/src/store.js, src/dispatch/static/dispatch/src/tag/store.js, src/dispatch/static/dispatch/src/tag_type/store.js, src/dispatch/static/dispatch/src/task/store.js, src/dispatch/static/dispatch/src/team/store.js, src/dispatch/static/dispatch/src/term/store.js, src/dispatch/static/dispatch/src/workflow/store.js
=> Adds initial version of the notifications UI

docs/configuration/plugins/configuring-slack.md
=> Fixing broken slack images

requirements-base.txt
=> Adding missing aiohttp dep

src/dispatch/static/dispatch/src/api.js, src/dispatch/static/dispatch/src/router/index.js
=> Setting a default provider to basic auth

src/dispatch/plugins/dispatch_slack/actions.py
=> Calls async version of get_user_email()

docker/Dockerfile
=> Ensure that the node binary exists in the final image

src/dispatch/incident_priority/views.py
=> Fixing an issue with incident priority update permission

src/dispatch/report/flows.py
Closes https://github.com/Netflix/dispatch/issues/844
=> Re-adds logic to send executive report to notifications group

.github/workflows/publish-image.yml, docker/Dockerfile, docker/docker-compose.yml
Fixes: #867 
See also: https://github.com/Netflix/dispatch-docker/pull/101
=> Aligning docker image on postgres-12

src/dispatch/incident/flows.py
=> Adds incident commander's team name to incident channel topic

src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
=> Adding document plugin check

src/dispatch/incident/scheduled.py
Cost will be updated only on incident state change open/stable/closed.
=> Removes incident cost update for external tickets

src/dispatch/config.py, src/dispatch/static/dispatch/src/incident_type/IncidentTypeCombobox.vue
=> Allows for n number of incident types

src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue, src/dispatch/static/dispatch/src/search/store.js
=> Fixing the tag filter string

src/dispatch/plugins/dispatch_slack/events.py, src/dispatch/plugins/dispatch_slack/socket_mode.py
=> Fixing support for socket mode events.

src/dispatch/auth/models.py
Closes https://github.com/Netflix/dispatch/issues/903.
=> Converts password from bytes to string before calling hash_password

src/dispatch/static/dispatch/src/incident/IncidentSummaryTable.vue, src/dispatch/static/dispatch/src/incident/Status.vue, src/dispatch/static/dispatch/src/router/config.js
Change fixes a bug where the incident summary table was attempting to show the edit incident pane.
=> Fixes incident new/edit pane

src/dispatch/incident/flows.py, src/dispatch/incident/messaging.py, src/dispatch/incident/scheduled.py, src/dispatch/messaging/strings.py, src/dispatch/report/flows.py, src/dispatch/report/messaging.py
=> Adds description and reporter to the welcome message and title, description, and reporter to list resources command

src/dispatch/incident/flows.py, src/dispatch/incident_type/models.py, src/dispatch/incident_type/views.py, src/dispatch/static/dispatch/src/incident_type/IncidentTypeMultiSelect.vue, src/dispatch/static/dispatch/src/individual/NewEditSheet.vue, src/dispatch/static/dispatch/src/team/NewEditSheet.vue
This PR adds some frontend and backend protections for restricted incident types.
=> Incident type restricted visibility protections

.dockerignore, docker/Dockerfile
=> Ensures the mjml is installed correctly on the core image

docs/configuration/app.md, docs/configuration/plugins/configuring-slack.md, src/dispatch/auth/models.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/service.py, src/dispatch/plugins/dispatch_slack/views.py, src/dispatch/plugins/dispatch_test/document_resolver.py, src/dispatch/route/service.py, src/dispatch/search/service.py, src/dispatch/tag/scheduled.py, src/dispatch/task/service.py, src/dispatch/team/models.py
These all appear to be in docstrings, comments, or documentation files, so no functional changes should result.
=> Various minor spelling corrections

src/dispatch/messaging/strings.py
=> Improves text and formatting of information review reminder

src/dispatch/static/dispatch/src/search/utils.js, src/dispatch/static/dispatch/src/tag/TagFilterCombobox.vue
By passing a "/" a tag combobox we can specify the type of tags to search against.
=> Adding the ability to scope tags while searching

src/dispatch/static/dispatch/src/incident/BulkEditSheet.vue, src/dispatch/static/dispatch/src/incident/api.js, src/dispatch/static/dispatch/src/incident/store.js
=> Adding the ability to bulk delete incident in the UI

src/dispatch/static/dispatch/src/incident_priority/NewEditSheet.vue
=> Fixes display issue with checkboxes in new incident priority UI

src/dispatch/auth/service.py
if "u" makes the sound of "you" than you should use "a" and not "an"
=> fixed typo

docs/admin-guide/administration/server.md
=> Fixing PKCE docs

src/dispatch/incident/views.py, src/dispatch/static/dispatch/src/incident/store.js
=> Adding exception logging

src/dispatch/plugins/dispatch_pagerduty/service.py
=> Adding better pagerduty message

src/dispatch/models.py, src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/definition/store.js, src/dispatch/static/dispatch/src/document/store.js, src/dispatch/static/dispatch/src/feedback/store.js, src/dispatch/static/dispatch/src/incident/IncidentMembersCombobox.vue, src/dispatch/static/dispatch/src/incident/IncidentResolveTimeCard.vue, src/dispatch/static/dispatch/src/incident/store.js, src/dispatch/static/dispatch/src/incident_cost_type/store.js, src/dispatch/static/dispatch/src/incident_priority/store.js, src/dispatch/static/dispatch/src/incident_type/store.js, src/dispatch/static/dispatch/src/individual/store.js, src/dispatch/static/dispatch/src/notification/store.js, src/dispatch/static/dispatch/src/plugin/store.js, src/dispatch/static/dispatch/src/project/store.js, src/dispatch/static/dispatch/src/service/store.js, src/dispatch/static/dispatch/src/tag/store.js, src/dispatch/static/dispatch/src/tag_type/store.js, src/dispatch/static/dispatch/src/task/store.js, src/dispatch/static/dispatch/src/team/store.js, src/dispatch/static/dispatch/src/term/store.js, src/dispatch/static/dispatch/src/workflow/store.js
- Make debounce period longer for table searching
- String any leading or trailing white space from pydantic models
- Fix tooltip text
=> Multiple fixes

src/dispatch/incident/service.py
Reformats incident service module to prevent black linting test from failing.
=> Reformats incident service module

src/dispatch/auth/models.py
Context: https://github.com/sqlalchemy/sqlalchemy/issues/6263#issuecomment-819645247
=> Replaces deprecated Binary symbol with LargeBinary

src/dispatch/plugins/dispatch_jira/plugin.py
=> Revert "Only get users that have permission"

requirements-base.txt
=> Revert "Bump sqlalchemy from 1.3.24 to 1.4.20"

src/dispatch/static/dispatch/src/document/reference/store.js, src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
=> Adds FAQ document link to incident submission form

src/dispatch/conversation/enums.py, src/dispatch/enums.py, src/dispatch/feedback/enums.py, src/dispatch/incident/enums.py, src/dispatch/messaging/strings.py, src/dispatch/notification/models.py, src/dispatch/participant_role/models.py, src/dispatch/plugins/dispatch_google/drive/drive.py, src/dispatch/plugins/dispatch_slack/modals/feedback/views.py, src/dispatch/plugins/dispatch_slack/modals/incident/enums.py, src/dispatch/plugins/dispatch_slack/modals/workflow/views.py, src/dispatch/report/enums.py, src/dispatch/task/enums.py, src/dispatch/workflow/models.py
Creates a new 'DispatchEnum' from which all other enums used by dispatch inherit from.
=> Creates a new 'DispatchEnum' 

src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
=> Adding rendered participants

src/dispatch/cli.py
By moving required imports to the function they are needed, we only incur import costs that are required to run the function.
=> Speeds up the responsiveness of cli commands

src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
This PR ensures we will pass the IncidentCreate -> ProjectRead Pydantic validation when a new incident is reported using the reporting form by querying the Project API and setting the id required by the ProjectRead model.
=> Queries Project API if project parameter is included in URL

src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
=> Revert "Queries Project API if project parameter is included in URL"

src/dispatch/models.py
Fixes https://github.com/Netflix/dispatch/issues/1563
=> Fixes OrganizationSlug regex

docker/Dockerfile
=> Fixes build errors induced by move to slim base image

docs/admin-guide/administration/incident/incident-type.md
Fixes https://github.com/Netflix/dispatch/issues/1627
=> Updates description for incident visibility

src/dispatch/database/revisions/tenant/versions/2021-10-05_ceaf01079f4f.py, src/dispatch/search_filter/models.py
=> Fixes database revision

src/dispatch/incident/flows.py, src/dispatch/incident/models.py, src/dispatch/incident/service.py
Fixes https://github.com/Netflix/dispatch/issues/1724
=> Adds resolved liaison and scribe roles to incident resources

src/dispatch/workflow/scheduled.py
Closes https://github.com/Netflix/dispatch/issues/1736
=> Improves logging in workflow scheduled jobs when plugin is not enabled

src/dispatch/auth/permissions.py, src/dispatch/static/dispatch/src/api.js
Closes https://github.com/Netflix/dispatch/issues/1924
=> Shows a forbidden message on resource edit when user role permissions are not sufficient

src/dispatch/organization/models.py, src/dispatch/organization/service.py, src/dispatch/static/dispatch/src/organization/CreateEditDialog.vue
=> Disables the name field when editing an organization

src/dispatch/static/dispatch/src/incident/IncidentWindowInput.vue, src/dispatch/static/dispatch/src/incident/Table.vue, src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
=> Improves incident filtering reliability

src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue, src/dispatch/static/dispatch/src/data/query/EditBasicInfoTab.vue, src/dispatch/static/dispatch/src/data/query/TableFilterDialog.vue, src/dispatch/static/dispatch/src/data/source/EditBasicInfoTab.vue, src/dispatch/static/dispatch/src/data/source/TableFilterDialog.vue, src/dispatch/static/dispatch/src/incident/DetailsTab.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/incident/TableExportDialog.vue, src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue, src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue, src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue, src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
Moves tag combo box to autocomplete.
=> Disables ad-hoc tag creation (e.g. combobox)

src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue, src/dispatch/static/dispatch/src/incident/IncidentActiveTimeCard.vue, src/dispatch/static/dispatch/src/incident/IncidentCommandersLocationBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentCostBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentForecastCard.vue, src/dispatch/static/dispatch/src/incident/IncidentHeatmapCard.vue, src/dispatch/static/dispatch/src/incident/IncidentParticipantsLocationBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentParticipantsTeamBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentPriorityBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentReportersLocationBarChartCard.vue, src/dispatch/static/dispatch/src/incident/IncidentResolveTimeCard.vue, src/dispatch/static/dispatch/src/incident/IncidentTagsTreemapCard.vue, src/dispatch/static/dispatch/src/incident/IncidentTypeBarChartCard.vue, src/dispatch/static/dispatch/src/task/TaskActiveTimeCard.vue, src/dispatch/static/dispatch/src/task/TaskIncidentPriorityBarChartCard.vue, src/dispatch/static/dispatch/src/task/TaskIncidentTypeBarChartCard.vue
=> Adds support for multi year charts and turns off animations to help performance.

src/dispatch/static/dispatch/src/dashboard/IncidentDrillDownTable.vue
- Fixes pagination issue
- Adds searching/filtering
=> Fixes a few issues with the incident dashboard drilldown table

src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
=> Hovering over a tag name shows its description and clicking on it opens its URI

docs/admin-guide/administration/incident/templates.md
Closes https://github.com/Netflix/dispatch/issues/2098
=> Updates the incident templates doc

docs/admin-guide/administration/incident/plugins/configuring-slack.md
=> Updates Slack documentation

src/dispatch/messaging/email/templates/executive_report.mjml
Updates the text in the executive report template to try to address situations where the recipient of the report is not directly added to the notifications distribution list but indirectly through a nested distribution list.
=> Updates executive report template text

src/dispatch/incident/flows.py
This PR addresses the first issue reported in this issue https://github.com/Netflix/dispatch/issues/2163
=> Dedupes resolved incident roles emails

src/dispatch/auth/views.py
Closes https://github.com/Netflix/dispatch/issues/2238
=> Fixes ability to change user's role

src/dispatch/database/manage.py, src/dispatch/main.py, src/dispatch/project/models.py, src/dispatch/project/service.py, src/dispatch/static/dispatch/src/project/NewEditSheet.vue, src/dispatch/static/dispatch/src/project/Table.vue
Closes https://github.com/Netflix/dispatch/issues/2239
=> Fixes an issue causing organization name to not being correctly extracted from request parameters

src/dispatch/incident/flows.py
Closes https://github.com/Netflix/dispatch/issues/2290
=> Logs a warning if ticket plugin is not enabled on ticket creation

src/dispatch/auth/models.py, src/dispatch/auth/permissions.py, src/dispatch/auth/service.py, src/dispatch/auth/views.py
Closes https://github.com/Netflix/dispatch/issues/2334
=> Fixes bugs impacting filtering users by organization and getting users' organization role

src/dispatch/search/fulltext/__init__.py
=> Revert "Flips the order in which we delete triggers and their associated functions"

src/dispatch/case/views.py, src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue, src/dispatch/static/dispatch/src/case/ReportForm.vue, src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/case/Status.vue, src/dispatch/static/dispatch/src/case/store.js, src/dispatch/static/dispatch/src/router/config.js
This PR duplicates functionality that we have with reporting incidents, allowing for the direct reporting of cases via a form.
=> Adds case reporting support

src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue, src/dispatch/static/dispatch/src/incident_type/IncidentTypeSelect.vue
These changes will enable case types in one project to be mapped to incident types in any project.
=> Enable case types in one project to be mapped to incident types in any project

docs/admin-guide/administration/plugins/configuring-slack.md
- Fix broken URLs
- Replace broken image link with table
=> Minor fixes to slack config

docs/admin-guide/administration/case/README.md, docs/user-guide/case.md
mitigation for #2575 while a more comprehensive documentation is not ready
=> add small descriptions of what Cases are

src/dispatch/search/fulltext/__init__.py
=> Revert "Disables dropping search triggers and functions"

src/dispatch/service/service.py
Sorted PagerDuty schedules that show while using `dispatch-engage-oncall` command
=> Sorted PD Schedule names

src/dispatch/case/models.py, src/dispatch/static/dispatch/src/case/EditSheet.vue, src/dispatch/static/dispatch/src/router/config.js, src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
=> Adds a way to view signal instances associated with a case.

src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Also fixes case types as well.
=> Ensures we only show enabled incident types

src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
=> Forces the user to specify the incident project

docker/Dockerfile
=> Updates the node version included in the docker file

src/dispatch/plugins/dispatch_core/plugin.py
=> Fixes an issue with the core dispatch ticket plugin

src/dispatch/static/dispatch/vite.config.js
Service workers cause issues for some SSO apps. Backing out this change for now.
=> Removing pwa

src/dispatch/static/dispatch/src/components/AppDrawer.vue, src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
=> Making the settings navbar more reliable

src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/data/query/QuerySelect.vue, src/dispatch/static/dispatch/src/data/source/SourceSelect.vue, src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatSelect.vue, src/dispatch/static/dispatch/src/data/source/environment/EnvironmentSelect.vue, src/dispatch/static/dispatch/src/data/source/status/StatusSelect.vue, src/dispatch/static/dispatch/src/data/source/transport/TransportSelect.vue, src/dispatch/static/dispatch/src/data/source/type/TypeSelect.vue, src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue, src/dispatch/static/dispatch/src/incident/IncidentSelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue, src/dispatch/static/dispatch/src/project/ProjectSelect.vue, src/dispatch/static/dispatch/src/tag_type/TagTypeSelect.vue
Fixes a bug with selects where if the initial selection isn't returned by the API it does not correctly select it.
=> v-select not setting initial select correctly

src/dispatch/conversation/models.py
=> Fixes conversation description

src/dispatch/plugins/dispatch_slack/endpoints.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
=> Deprecates Slack slash command dispatch-list-resources in favor of channel bookmarks

src/dispatch/static/dispatch/src/case/BulkEditSheet.vue, src/dispatch/static/dispatch/src/case/HandoffDialog.vue, src/dispatch/static/dispatch/src/case/store.js
=> Adds support for handing off cases in bulk

.pre-commit-config.yaml, requirements-dev.in, requirements-dev.txt
```
(dispatch) $ > dispatch % pre-commit run --all-files                                          
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/charliermarsh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
ruff.....................................................................Passed
```
=> add .pre-commit.config.yaml for `black`, `ruff`, and `pytest`

src/dispatch/static/dispatch/src/signal/TableInstance.vue
=> Add Filter Action column to SignalInstance table

src/dispatch/entity/service.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, tests/entity/test_entity_service.py
We also add some missing types to entity service
=> Only show entities for the subject Signal type on snooze button Slack modal

src/dispatch/static/dispatch/src/entity/EntitiesTab.vue, src/dispatch/static/dispatch/src/entity/EntityCard.vue
=> group entities and display a counter in the card

src/dispatch/case/flows.py, src/dispatch/conversation/service.py, src/dispatch/participant/flows.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/plugins/dispatch_slack/middleware.py
This PR fixes breaking changes ([here](https://github.com/Netflix/dispatch/pull/2913/files#diff-be932aea97556035df57c47ea4fa56c2ca3b7441226f65595ef4ef2f48c422ab) and [here](https://github.com/Netflix/dispatch/pull/2913/files#diff-4cef4776fc86766f7ccd0412bfe00a095a19cc90145629e0a3cf6b35081c8913)) introduced in this [PR](https://github.com/Netflix/dispatch/pull/2913).
=> Fixes breaking changes impacting incident ban threads feature

src/dispatch/plugins/dispatch_slack/plugin.py
See: https://github.com/Netflix/dispatch/issues/3343
=> handle cases where the Email Display setting is unchecked in Slack Admin settings

requirements-base.txt
=> Revert "Bump pdpyras from 4.5.2 to 5.0.1"

src/dispatch/static/dispatch/src/entity_type/EntityTypeSelect.vue
=> Makes the entity type select have a type ahead

src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
Need to add pagination to the Signal tab table as there can be thousands.
=> Add pagination to mini signal table tab

src/dispatch/plugins/dispatch_slack/workflow.py, src/dispatch/workflow/service.py
Fix workflow params to parse the keys correctly
Send few incident metadata as part of the workflow params payload
Save the workflow run reasons
=> workflow related fixes

src/dispatch/plugins/dispatch_slack/case/interactive.py
=> Fixes sending duplicate resolved messages

src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/service.py
=> Pass Slack Client to `does_user_exist` function

src/dispatch/plugins/dispatch_slack/case/interactive.py
=> Resolve reporter for cases created via Slack shortcut

src/dispatch/plugins/dispatch_slack/middleware.py
Fixes issue with middleware crash
=> Skips select context parsing if not a select message

src/dispatch/static/dispatch/src/filters.js, src/dispatch/static/dispatch/src/incident/ParticipantsTab.vue
=> Shows Inactive instead of empty string in the participants tab when a participant is inactive

src/dispatch/signal/flows.py, src/dispatch/signal/service.py, src/dispatch/signal/views.py
This adds very basic signal update functionality (essentially making sure we are updating entities). Further improvements that could be made:
- A case timeline notification that a signal was updated
- A message in the case thread that a signal was updated
- Reopen a case if a signal is updated
I've left these off for simplicity, but also because I think they could very easily become confusing to whoever is triaging. I think this step allows us to capture the changed data while we think through what (if any) other behaviors we want to tie to a signal update.
=> Allows for signals to be updated

src/dispatch/auth/permissions.py
Allows incident participants to view the details of an incident even when the visibility of the incident is marked as restricted.
=> Adds new incident participant permission

src/dispatch/search/models.py, src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue, src/dispatch/static/dispatch/src/search/ResultList.vue
This adds cases to the global search results.
=> Add cases to search results

src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/components/AppToolbar.vue
Replacing the URL of the avatar with the correct format and using icon for default if it doesn't exist. In the future, we might want to have the avatar URL configurable in the UI.
=> Replaces avatar URL with correct format

src/dispatch/plugins/dispatch_slack/incident/enums.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
This PR adds a hook for a Report Incident Slack shortcut.
=> Adding ability to report incident from shortcut

src/dispatch/document/flows.py, src/dispatch/incident/flows.py
This PR adds support for opening access and marking incident review documents as readonly on incident close if configured as such in the project's storage plugin. Additionally, refactors and moves logic to the document flows module.
=> Adds support for opening access and marking incident review documents as readonly

src/dispatch/report/scheduled.py
This bugfix checks the manual report reminder (snooze) to see if there exists a snooze set in the future, if so, it skips the regularly scheduled reminder. If the snooze is for some reason set to a time in the past, the regularly scheduled reminder is sent and the snooze time is reset to null.
=> Checking for manual snooze on report reminder before sending regularly scheduled one

requirements-base.txt, src/dispatch/incident/flows.py, src/dispatch/tag/flows.py
This PR records added and/or removed tags in the timeline. The description is just a summary of the number of added/removed tags and the details show the actual tags that were added/removed.
=> Record added and removed tags in timeline

src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue, src/dispatch/static/dispatch/src/dashboard/incident/IncidentsDrillDownSheet.vue
Fixes the drill down pane that was erroneously not closing correctly.
=> Fixing drill down pane not closing issue

src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/static/dispatch/src/incident/store.js
Previously, user input was overwritten by the list of outstanding incident tasks. This PR preserves user input and appends outstanding incident tasks to user input in tactical reports.
=> Appends outstanding incident tasks in tactical reports

src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Reverts Netflix/dispatch#3799 - will combine into new PR
=> Revert "Making experience textbox from oncall end-of-shift feedback optional"

src/dispatch/static/dispatch/src/signal/Table.vue
=> Adds Create Case checkbox to Signal Definition table

src/dispatch/static/dispatch/package-lock.json, src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue, src/dispatch/static/dispatch/src/incident_role/Table.vue
=> Do not print out raw role policies in the incident roles UI section

src/dispatch/plugins/dispatch_aws/plugin.py
Fixes an issue where if an exception is raised during ingestion it can invalidate the session and prevent further processing.
=> Rollback session in case of exceptions

src/dispatch/static/dispatch/src/case/ParticipantsTab.vue, src/dispatch/static/dispatch/src/case/ResourcesTab.vue, src/dispatch/static/dispatch/src/incident/ParticipantsTab.vue, src/dispatch/static/dispatch/src/incident/ResourcesTab.vue
Fixing spacing on Resources and Participants tabs in both incidents and cases view/edit screens.
=> Adding padding for spacing on participants and resources tabs

src/dispatch/static/dispatch/src/case/TableExportDialog.vue, src/dispatch/static/dispatch/src/incident/TableExportDialog.vue, src/dispatch/static/dispatch/src/task/TableExportDialog.vue
Ensuring that Export for incidents, cases, and tasks have scroll bars.
=> Fixing export preview missing scroll for incidents, cases, and tasks

src/dispatch/static/dispatch/src/incident/priority/Table.vue, src/dispatch/static/dispatch/src/plugin/Table.vue, src/dispatch/static/dispatch/src/search/EditDialog.vue
Fixes styling issues with missing scroll bars and alignment.
=> Fixing styling for incident priority settings, search filter settings, and plugins table

src/dispatch/static/dispatch/src/case/type/Table.vue, src/dispatch/static/dispatch/src/document/template/TemplateNewEditSheet.vue, src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue, src/dispatch/static/dispatch/src/incident/type/Table.vue
This PR fixes the issue with the new template dialog always appearing in the places where the template selector is being used.
=> Fixing issue with new template dialog always appearing

src/dispatch/static/dispatch/src/plugin/store.js
This PR removes token masking from plugin data fields.
=> Removing password element from plugin form

requirements-base.txt
=> Revert "Bump alembic from 1.12.0 to 1.12.1"

tests/static/e2e/pages/auth-page.ts, tests/static/e2e/pages/incident-edit-sheet.ts, tests/static/e2e/pages/incidents-page.ts, tests/static/e2e/pages/report-incident-page.ts
=> Fixing playwright tests

src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue, tests/static/e2e/pages/report-incident-page.ts, tests/static/e2e/report-submission.spec.ts
Continued work on fixing playwright tests for Vue 3
=> Fixing playwright tests part 2

src/dispatch/static/dispatch/src/entity/EntityFilterCombobox.vue
=> Show entity value in entity filter combobox

src/dispatch/static/dispatch/src/components/AppDrawer.vue, src/dispatch/static/dispatch/src/components/SettingsBreadcrumbs.vue, src/dispatch/static/dispatch/src/project/ProjectMenuSelect.vue
=> Fixing settings bread crumbs

src/dispatch/static/dispatch/src/components/AppToolbar.vue
This fixes the issue where the dark mode was not persisting through page reloads.
=> Dark mode not persisting through reloads

src/dispatch/signal/flows.py
Deduplicating signal instances should only occur when those instances are associated with a case.
=> Fixes signal instance deduplication check.

src/dispatch/static/dispatch/src/case/TimelineTab.vue
=> Add UTC hover to relative times in timeline

src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
=> Renames Investigation Write-Up to Resolution and move button to top

src/dispatch/static/dispatch/package-lock.json, src/dispatch/static/dispatch/package.json, src/dispatch/static/dispatch/src/tests/LockButton.spec.js, src/dispatch/static/dispatch/vitest.config.js
```bash
✓ src/tests/LockButton.spec.js (2)
✓ mounts correctly
✓ opens dialog on button click
Test Files  1 passed (1)
Tests  2 passed (2)
Start at  09:18:52
Duration  853ms
```
=> Adds vitest proof-of-concept for LockButton component

src/dispatch/static/dispatch/src/signal/TableFilterDialog.vue, src/dispatch/static/dispatch/src/signal/TableInstance.vue, src/dispatch/static/dispatch/src/signal/store.js
=> Adds filtering support by signal definition to signal instance table

src/dispatch/static/dispatch/src/case/Table.vue, src/dispatch/static/dispatch/src/case/TableFilterDialog.vue, src/dispatch/static/dispatch/src/case/store.js
In preparation for other improvements.
=> [Case] - Refactor table to use script setup v3 api

src/dispatch/plugins/dispatch_slack/case/messages.py
Prior change did not fix the issue
=> Fix bug in slack response plan button

src/dispatch/static/dispatch/src/case/Table.vue
Adds back search to the Case table
=> Adds watcher back to query variable on Case table

src/dispatch/incident_cost/service.py
Change logging level from info to debug for incident cost calculations.
=> Reduce logging noise for incident cost calculation.

src/dispatch/static/dispatch/src/case/Table.vue, src/dispatch/static/dispatch/src/incident/Table.vue
This PR replaces the NEW button on the incident and case pages with a REPORT button that links directly to the simplified report form.
=> Change new button on incident and case pages to point to report form

src/dispatch/plugins/dispatch_slack/case/interactive.py
=> Fixes case escalate modal submission

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Fixes error from accessing a None type object by moving outstanding_action initialization outside an if statement.
=> Fixes error from accessing a None type object.

src/dispatch/plugins/dispatch_slack/case/interactive.py
This gap is causing `triage_at` to not be set correctly.
=> Force cases resolved via user enagement to follow case flows

src/dispatch/static/dispatch/package-lock.json
=> Revert "Bump vite from 5.0.12 to 5.1.3 in /src/dispatch/static/dispatch"

src/dispatch/static/dispatch/package-lock.json
=> Revert "Bump vue from 3.4.15 to 3.4.19 in /src/dispatch/static/dispatch"

src/dispatch/plugins/dispatch_slack/service.py
Add try again for request timeouts to slack
=> handle network timeouts in slack make_call

src/dispatch/plugins/dispatch_slack/case/interactive.py
When the triage button is clicked we need to set triage_at.
=> Fixing triage button transition

requirements-base.txt, requirements-dev.txt
=> Python packages update

requirements-base.txt, requirements-dev.txt
=> Revert "Python packages update"

src/dispatch/plugins/dispatch_slack/case/interactive.py
This PR ensures that the transition flow is run when moving to the triage state.
=> Run transition flow to move to triage state

src/dispatch/static/dispatch/src/forms/store.js
This PR adds a new attribute to the forms, allowing the user to enter a new value to a dropdown list.
=> Adding new form type that allows new values

.github/workflows/python.yml
Dispatch's current code coverage is 54%. This PR enforces code coverage to not drop below the current amount.
=> Enforces minimum code coverage.

src/dispatch/signal/views.py
=> pass signal.id on delete

src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Ensure that the case type will repopulate with correct types from project when user changes the project.
=> Fixing Report Case card to ensure case type reflows on project change

src/dispatch/plugins/dispatch_slack/service.py
Added another exception object for TimeoutError
=> Adding TimeoutError handling

src/dispatch/participant_role/enums.py
=> bugfix: case participants added to incidents should be participant role not observer

src/dispatch/static/dispatch/src/forms/store.js
Adds incident cost to the Incident Information section on the attorney review form.
=> Adds incident cost to the attorney review form

src/dispatch/case/flows.py, src/dispatch/case/messaging.py, src/dispatch/plugins/dispatch_slack/case/interactive.py
Rewrite the case participant welcome message to be sent from the `case_add_or_reactivate_participant_flow` function, similar to incidents.
=> Rewrite case welcome into add_or_reactivate flow

src/dispatch/case/flows.py
Adding logging to debug when some cases do not get a triaged_at time.
=> Add logging for case status transitions

src/dispatch/case/flows.py
Recommended update to structured data being added to the logging instead of including it in the message directly
=> Adding structured data

src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
This PR modifies the case type select to show the team associated with the case type, if specified.
=> Organize case select by oncall team

src/dispatch/plugins/dispatch_slack/config.py
Redefining max limit on dialog text to below 3000.
=> Modifying max limit

src/dispatch/static/dispatch/src/case/EditSheet.vue, src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
This PR sets case cost model as an experimental feature.
=> Case cost model is an experimental feature.

src/dispatch/case/flows.py
This PR fixes a bug in `map_case_roles_to_incident_roles` which used the wrong type.
=> Fixing participant role type in mapping function

src/dispatch/participant/flows.py
This PR fixes the formatting for the participant additions in the timeline.
=> Fixing role formatting for timeline event

src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
Similar to PR #5166 this PR adds the project filters to type, severity, and priority on the dashboard filter dialog.
=> Adds project to comboboxes in dashboard filters

src/dispatch/incident/scheduled.py
=> Correcting import for Session

src/dispatch/incident/scheduled.py
Corrects a typo in the AI plugin endpoint used for the weekly summary.
=> fix(scheduler): corrects endpoint for weekly summary

src/dispatch/incident/scheduled.py
Fixes the prompt in the weekly summary.
=> fix(scheduler): adapting weekly summary to new ai parameters

src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Correctly parses python object.
=> fix(scheduler): use ast instead of json library to load string data

src/dispatch/signal/models.py, src/dispatch/signal/service.py, src/dispatch/signal/views.py
This pull request includes several changes to the `src/dispatch/signal` module to improve code organization and add new functionality for managing signal engagements. The most important changes include reordering imports for better readability, adding a new `SignalEngagementUpdate` class, and updating service and view functions to support updating signal engagements.
* [`src/dispatch/signal/models.py`](diffhunk://#diff-7515ae179456ca6dcf748bda87b177d0b19aacee486ae063a22ea842467e1ecfL3-L12): Reordered imports for better readability and consistency. [[1]](diffhunk://#diff-7515ae179456ca6dcf748bda87b177d0b19aacee486ae063a22ea842467e1ecfL3-L12) [[2]](diffhunk://#diff-7515ae179456ca6dcf748bda87b177d0b19aacee486ae063a22ea842467e1ecfL27-R41)
* …
=> Allows to update a signal engagement

src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue, src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
This seems better; I was able to replicate the lock-up that we experienced locally. But am unable to now... 🤞🏻
=> Fixing case/incident report selects.

src/dispatch/search/views.py
=> fix(search): only collect participant emails if individual exists

src/dispatch/plugins/dispatch_core/plugin.py, src/dispatch/plugins/dispatch_jira/plugin.py, src/dispatch/plugins/dispatch_jira/templates.py, src/dispatch/ticket/flows.py
This PR adds a link to the Dispatch UI in the incident and case Jira tickets. Fixes DISDEV-364.
=> feat(jira): add Dispatch link in Jira ticket

src/dispatch/static/dispatch/src/components/GenaiAnalysisDisplay.vue
This PR fixes a few prettier linting errors.
=> fix(ui): fixing linting errors

.github/workflows/python.yml, src/dispatch/static/dispatch/src/case/DetailsTab.vue, src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue, src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/incident/DetailsTab.vue, src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
This PR locks the project field in the Details tab for both incidents and cases and fixes the type and priority dropdowns.
=> fix(ui): fixes details tab selects

data/dispatch-sample-data.dump, src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue, tests/static/e2e/fixtures/dispatch-fixtures.ts, tests/static/e2e/pages/report-case-page.ts, tests/static/e2e/report-case.spec.ts, tests/static/e2e/routes.ts
This PR tests reporting a case. Note: dependent on https://github.com/Netflix/dispatch/pull/5434 for database changes.
=> tests(case): adds case reporting test

src/dispatch/static/dispatch/src/case/TableFilterDialog.vue, src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue, src/dispatch/static/dispatch/src/router/utils.js, src/dispatch/static/dispatch/src/search/utils.js
This PR allows incidents and cases to be filtered on multiple participants/incident commanders/assignees.
=> enhancement(ui): allow multiple assignee and participants

src/dispatch/static/dispatch/package-lock.json
=> Revert "chore(deps): bump vuetify from 3.7.3 to 3.7.4 in /src/dispatch/static/dispatch"

src/dispatch/static/dispatch/src/auth/Mfa.vue
=> fix(ui): self closing tag

src/dispatch/plugins/dispatch_aws/plugin.py
Fixes logic introduced in https://github.com/Netflix/dispatch/pull/5523
=> bugfix(aws-sqs-signal-consumer-plugin): fixes logic

src/dispatch/incident/service.py
Adding a list of words to avoid in incident summaries.
=> feat(ai): tune prompt for incident summary

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Fixes a bug when `individual` is not defined.
=> fix(slack): individual may not be defined

src/dispatch/document/flows.py
=> fix(document): ensure document exists before acting on it

src/dispatch/static/dispatch/src/forms/store.js
This fixes an issue where the form from the table view wouldn't save because the project wasn't available on the selected object.
=> fix(forms): get project from form_type

src/dispatch/main.py
=> feat(db): adds support for database session tracking in middleware

src/dispatch/static/dispatch/src/case/store.js
This pull request introduces a missing action to the `actions` object in the `case/store.js` file to enhance state management for case selection, to provide parity with Incidents.
=> fix(cases): Report Another Issue functionality

src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/events/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
My local instance is borked, but will this fix the button spacing @aaronherman ?
=> Nit: equal spacing on both button sides.
