Netflix/dispatch

setup.py
Thanks for creating useful library. As it already runs on Python 3.8 in CI I think it is good to add Python 3.8 classifier.
=> Add Python 3.8 classifier

Dockerfile, docs/installation.md
The project Dockerfile lives in a `./docker` directory, but references
files hosted in the root directory, namely:
- `.nvmrc`
- `setup.py`
Dockerfiles can only reference files in the same folder as the build
context. This results in build errors reported in
https://github.com/Netflix/dispatch-docker/issues/2 and initially
addressed in https://github.com/Netflix/dispatch-docker/pull/1
```
ERROR: Service 'web' failed to build: COPY failed: stat
/var/lib/docker/tmp/docker-builder448268992/.nvmrc: no such file or
directory
```
This is a simple fix to move the Dockerfile into a reasonable scope via
symlink. However, open source contributors cannot build the image
locally since the build steps appear rely on access to resources on
Netflix internal network.
=> Fix Docker build directory visibility

docker/Dockerfile, docker/docker-entrypoint.sh
Summary of changes:
- improve parsing in startup script
-- fix how 2-word commands are parsed by bash
-- add the "scheduler" command as a recognized command to support the scheduler container in [docker-compose](https://github.com/Netflix/dispatch-docker/blob/f65df7ca90e51ae2c72e87175efb5c275e6b21e0/docker-compose.yml#L20-L21)
- exclude the `.env` file in the build step
-- adjustments to the environment file shouldn't trigger a rebuild since it configures run-time settings
-- it's not used for the build
-- the file is more appropriately supplied at run-time via `docker run` or via `docker-compose`
- set the default command
-- reading through the [documentation](https://hawkins.gitbook.io/dispatch/cli#start) it appears this image is trying to boot up the server as the default invocation
-- …
=> Fix docker image startup

docker/Dockerfile, src/dispatch/run.py
This allows us to reach dispatch behind a reverse proxy and fixes: https://github.com/Netflix/dispatch-docker/issues/19
=> fix uvicorn port binding for docker

docs/configuration/configuration.md
Environment variable VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL is used in the vue app, not VUE_APP_DISPATCH_OPEN_ID_CONNECT.
=> fix env key in doc

.gitignore, src/dispatch/cli.py, src/dispatch/incident/flows.py, src/dispatch/incident/models.py, src/dispatch/incident/service.py, src/dispatch/incident/views.py, src/dispatch/plugins/dispatch_jira/plugin.py, src/dispatch/plugins/dispatch_slack/config.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/views.py, src/dispatch/static/dispatch/src/incident/Table.vue, src/dispatch/static/dispatch/src/incident/store.js
When updating the stable_at field, we were always setting this field to be utcnow(), this first checks for an existing stable_at before setting the field.
=> Fixing issue where stable time would always be overwritten with utcnow()

src/dispatch/cli.py, src/dispatch/incident/scheduled.py, src/dispatch/incident/service.py
The actual query should be pretty cheap (on a five minute interval), but we make sure that we don't update external resources if the cost hasn't changed.
=> Update costs no matter the status.

src/dispatch/cli.py
We want to allow simple in-place upgrades, running the `database upgrade` command will get the database up to date even if it doesn't yet exist.
=> Allows upgrade to create the database if it doesn't exist.

src/dispatch/document/models.py
=> Only use the default description when one is not set.

src/dispatch/cli.py
This small patch fixes the database dump command to use the configured DATABASE_NAME instead of the hard coded `dispatch` name.
=> Fix dump database to use DATABASE_NAME from config

src/dispatch/cli.py
I'm experimenting with dispatch for internal use at [work](https://www.platform.sh). We want to be able to deploy it in our own infrastructure and I ran into an issue during db initialization. The `dispatch database initi` code assumes the user has permissions to create/delete databases. In a PaaS like Platform.sh, you already start with an existing database and the user doesn't have permission to create new ones. Only to create/delete tables. This patch makes database init work during deployment in such case. Do you think this is the right thing to do? If you would prefer another direction, please let me know. I can further describe the use case as well.
Any feedback much appreciated! Thanks for the work on this.
=> skip db creation in init if already exist

docs/configuration/configuration.md, src/dispatch/config.py, src/dispatch/incident/flows.py, src/dispatch/plugins/dispatch_google/drive/drive.py, src/dispatch/plugins/dispatch_google/drive/plugin.py
* This PR introduces a new configuration variable called `INCIDENT_STORAGE_RESTRICTED`, which controls whether a set of restrictions and capabilities to prevent content sharing need to be applied on the incident storage.
* This variable is set to `True` by default. You can disable it by setting `INCIDENT_STORAGE_RESTRICTED` to `False` in your `.env` file.
=> Adds ability to restrict access to and sharing of content in the incident drive

src/dispatch/plugins/dispatch_google/calendar/plugin.py
Google APIs tend to have eventual consistency problems. As we are creating several interrelated resources fairly quickly, we have to be aggressive about what we retry. Here we essentially retry up to 3 times for any google calendar API error (including things like 404).
=> Be more aggressive with google calendar api retries

requirements-base.txt, requirements-metrics.txt, setup.py
This allows our heavy weight metric dependencies to be optionally installed via `pip install -e .[metrics]`
=> Allowing some heavy weight metric libraries to be opt-in.

docker/Dockerfile
This way we can run dispatch database commands from the dispatch
container (if you have a database set up somewhere else)
=> Include postgresql-client as dependency.

src/dispatch/common/utils/cli.py, src/dispatch/messaging.py, src/dispatch/plugins/dispatch_pagerduty/service.py, src/dispatch/service/models.py
Found some minor bugs with LGTM.
Fixed 2 of the three `multiple variable definition`:
https://lgtm.com/projects/g/Netflix/dispatch/alerts/?mode=tree&ruleFocus=1800095&id=py%2Fmultiple-definition
Removed a redundant import:
https://lgtm.com/projects/g/Netflix/dispatch/alerts/?mode=tree&id=py%2Frepeated-import&ruleFocus=7890086
`dispatch_pagerduty/service.py` forgot the `raise` keyword before instantiating a `DispatchPluginException` object:
https://lgtm.com/projects/g/Netflix/dispatch/alerts/?mode=tree&id=py%2Funused-exception-object&ruleFocus=1505923886371
=> Bugfix. Variables w/multiple definitions.

data/dispatch-sample-data.dump, src/dispatch/cli.py
This patch fixes the sample data ownership to the default user used by dispatch `postgres` and fix the restore command to use the DATABASE_NAME env var.
=> Fix restore and sample data

src/dispatch/static/dispatch/src/definition/NewEditSheet.vue, src/dispatch/static/dispatch/src/document/NewEditSheet.vue, src/dispatch/static/dispatch/src/incident/NewEditSheet.vue, src/dispatch/static/dispatch/src/incident/ReportForm.vue, src/dispatch/static/dispatch/src/incident_priority/NewEditSheet.vue, src/dispatch/static/dispatch/src/incident_type/NewEditSheet.vue, src/dispatch/static/dispatch/src/individual/NewEditSheet.vue, src/dispatch/static/dispatch/src/service/NewEditSheet.vue, src/dispatch/static/dispatch/src/tag/NewEditSheet.vue, src/dispatch/static/dispatch/src/task/NewEditSheet.vue, src/dispatch/static/dispatch/src/team/NewEditSheet.vue, src/dispatch/static/dispatch/src/term/NewEditSheet.vue
With the update to veevalidate 3.x we need to explicitly import our validation rules (including `required`).
See: 
https://logaretm.github.io/vee-validate/#usage
=> Ensuring we are enforcing require fields.

src/dispatch/cli.py
=> Reads variables from .env file as well as envvars

setup.py
This was causing errors for setup tools, looks like it was a missed typo since the option is `zip_safe`.
`/usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_save'
warnings.warn(msg)
`
=> fix typo in setup.py option

src/dispatch/plugins/base/manager.py
Encountering pydantic errors when trying access plugin page as enabled column is empty. This PR assures that enabled column will always have a value.
=> Fixed empty enabled column in table 'plugin'

src/dispatch/plugins/base/manager.py, src/dispatch/static/dispatch/src/router/index.js
Currently if auth provider is set to dispatch-auth-provider-basic if the requestor is not authenticated, the requestor will remain hanging trying to access /login page.
e.g 
User is unauthorized gets redirect to "/login" from L143 after this the hook on routerBefore will be called again but this time the path.to is "/login" thus the router will actually have no resolve at all, and next() is never called.
=> Bugfix router login redirect

src/dispatch/plugins/dispatch_zoom/plugin.py
Add `author` and `author_url` to the zoom plugin to fix the plugins page. Without this it fails with 
```
response -> items -> 0 -> author
none is not an allowed value (type=type_error.none.not_allowed)
response -> items -> 0 -> author_url
none is not an allowed value (type=type_error.none.not_allowed)
```
=> Add author and author URL to zoom plugin to fix plugins page

docker/Dockerfile
Fix a syntax issue in the Dockerfile, switch to sks-pools for the keyserver as several keys were missing from keys.openpgp.org (including the one for `gosu`)
Removed the bits messing with `$GPUGPHOME` since it didn't seem necessary and none of the other steps did anything similar.
Closes #340
=> switch gpg keyserver due to missing keys, fix syntax error in dockerfile

docs/configuration/app.md, src/dispatch/plugins/dispatch_core/config.py, src/dispatch/plugins/dispatch_core/plugin.py
Adds the ability to include an audience in `jwt.decode` as well as not rely on email address to be in `email` key of the JWT.  This also adds the support for key rotation when the IDP sends back more than one key in the key fetch.
=> Add PKCE overrides and support the key rotation

src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/service.py
`slackclient` requires tokens to be strings, but they're currently `Secret`s.  `__str__()` seems to be implemented on `Secret` to return the value itself (or decrypted value if using some sort of KMS), so we should be able to just cast these at usage-time.
Stacktrace that current `develop` emits:
```
ERROR:dispatch.common.utils.cli:Failed to load plugin slack_contact:Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/dispatch/common/utils/cli.py", line 34, in install_plugins
plugin = ep.load()
File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
return self.resolve()
File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
module = __import__(self.module_name, fromlist=['__name__'], …
```
=> Cast Secret to string for Slack bot tokens

src/dispatch/individual/service.py, src/dispatch/participant/service.py, src/dispatch/plugins/dispatch_slack/plugin.py
This PR fixes a `NoneType` exception when Slack fields are `None`.
=> Checks Slack profile fields for None before accessing them

src/dispatch/static/dispatch/src/incident/Status.vue
=> Adds last executive report to active incidents status page

src/dispatch/incident/flows.py, src/dispatch/incident/scheduled.py, src/dispatch/plugins/dispatch_jira/plugin.py
This PR removes all Netflix-specific, Jira custom fields from the Jira plugin and moves the data stored on those fields to the Jira issue summary template. It also reduces the amount of parameters passed to `update_external_incident_ticket()` in the `incident.flows` module.
=> Removes Netflix-specific, custom Jira fields from Jira plugin

src/dispatch/conversation/enums.py, src/dispatch/plugins/dispatch_google/drive/drive.py, src/dispatch/plugins/dispatch_google/drive/plugin.py, src/dispatch/plugins/dispatch_slack/actions.py, src/dispatch/plugins/dispatch_slack/commands.py
This adds `resolve` and `reopen` buttons to the output of `list-my-tasks` and `list-tasks` commands and allows a user to set the status of a task from the incident channel itself.
We do not add these buttons to the "New Task" or "Resolved Task" notifications at this time.
=> Initial work on allowing tasks to be resolve by dispatch.

src/dispatch/plugins/dispatch_jira/plugin.py
`src/dispatch/incident/flows.py` was updated in https://github.com/Netflix/dispatch/pull/430 and named parameters were changed to ordered parameters in the call to `plugin.instance.update(`.  This simply fixes the parameter order in `JiraTicketPlugin.update` so the links match the same call in `dispatch_jira/plugin.create_issue_fields` and `src/dispatch/incident/flows.py`
=> updated JiraTicketPlugin.update parameter order to match pull 430

src/dispatch/incident/flows.py
Let's keep the participant groups (tactical and notifications) on incident close to ensure participants have access to the incident folder and its contents.
=> Keeps participant groups on incident close

src/dispatch/plugins/dispatch_google/drive/drive.py
Re-adding parameter `supportsAllDrives`, which according to these [docs](https://developers.google.com/resources/api-libraries/documentation/drive/v3/python/latest/drive_v3.files.html) is deprecated, but the code doesn't work without it.
> supportsAllDrives: boolean, Deprecated - Whether the requesting application supports both My Drives and shared drives. This parameter will only be effective until June 1, 2020. Afterwards all applications are assumed to support shared drives.
=> Re-adds supportsAllDrives param for G Drive API calls

src/dispatch/document/scheduled.py, src/dispatch/plugins/dispatch_slack/modals.py
Related to https://github.com/Netflix/dispatch/pull/507, fix a typo for `group` plugin type and remove the `INCIDENT_PLUGIN_STORAGE_SLUG` from document scheduler.
=> Remove INCIDENT_PLUGIN_STORAGE_SLUG and fix group plugin typo

SUMMARY.md, docs/installation.md
While reading docs, fixed a few typos/syntax and a bad link.
Not worth a new release.  I'm sorry if I come off as a "Linter" (no impact beyond spellcheck) but it stands out to me and this may be what little I can contribute :)
=> Fix Doc Typos

src/dispatch/plugins/dispatch_google/drive/task.py
We used to rely on the + char to indicate all assignees to a google comment/task. Recently now relies on @ instead of +.
=> Google now converts + to @

src/dispatch/conversation/service.py, src/dispatch/plugins/dispatch_slack/actions.py, src/dispatch/plugins/dispatch_slack/events.py, src/dispatch/plugins/dispatch_slack/views.py
Slack changes the channel type from private `G` to public `C` when the `Share Channel` modal is _opened_. Slack doesn't send the `channel_shared` event until the share process is completed by the external party. This breaks all logic that relies on the channel id stored in the Dispatch database.
This PR adds logic to fetch the Slack conversation ignoring the channel type and updates the channel id in the database if the channel type has changed.
=> Fetches Slack conversation ignoring channel type

src/dispatch/conversation/service.py, src/dispatch/plugins/dispatch_slack/actions.py, src/dispatch/plugins/dispatch_slack/events.py, src/dispatch/plugins/dispatch_slack/views.py
* Removes unused or unimplemented code
* Adds after hours
* Fetches conversation by channel id ignoring channel type
* Adds event to timeline
=> [Hotfix] Fetches Slack conversation ignoring channel type (#560)

src/dispatch/plugins/dispatch_slack/events.py
Slacks sends a `member_joined_channel` event when a channel member clicks on "Share Channel". The inviter key in the event is not set. This PR adds logic to check that inviter has a value before trying to update the participant's metadata.
=> Checks if inviter exists before updating participant's metadata

src/dispatch/plugins/dispatch_slack/commands.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/modals.py, src/dispatch/plugins/dispatch_slack/service.py, src/dispatch/plugins/dispatch_slack/views.py
This PR adds logic to handle commands when they're run from non-incident channels or channels where Dispatch bot is not present.
=> Handles commands run in non-incident channels

requirements-base.txt, src/dispatch/plugins/bases/oncall.py, src/dispatch/plugins/dispatch_opsgenie/plugin.py, src/dispatch/plugins/dispatch_pagerduty/config.py, src/dispatch/plugins/dispatch_pagerduty/plugin.py, src/dispatch/plugins/dispatch_pagerduty/service.py, src/dispatch/plugins/dispatch_test/oncall.py
I've removed resolution by `service_name` because dispatch never passes such a value. If we want to support service name in the future it would be by detecting a name via the `service_id` value.
=> Migrates to the pdpyras client library

src/dispatch/incident/models.py, src/dispatch/static/dispatch/src/tag/TagFilterCombobox.vue, src/dispatch/tag/models.py
Replaces `Any` with `TagRead` in the `IncidentRead` Pydantic model to ensure we get the whole `Tag` object and any related objects such as `TagType` in the UI. Also fixes typo in `TagFilterCombobox`.
=> Fixes bug when tagging incidents

src/dispatch/plugins/dispatch_slack/service.py, src/dispatch/plugins/dispatch_slack/views.py
When a non-incident / command is run, we check if it was run in one of the public or private conversations the Dispatch bot is a member of. If it wasn't run from one of those channels, we send the user a list of public conversations they can run the command. We don't include the list of private ones, because we don't want to expose them.
=> Ensures non-incident commands can be run from all conversations where the bot is present

src/dispatch/plugins/dispatch_slack/service.py, src/dispatch/plugins/dispatch_slack/views.py
Handles a situation where a user tries to run a non incident specific command such as `/dispatch-list-incidents` in a private channel where Dispatch bot is not a member of.
=> Slack Commands: Handles channel not found error

src/dispatch/incident/scheduled.py, src/dispatch/messaging.py, src/dispatch/plugins/dispatch_slack/commands.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/modals.py
Leverages the new `header` block type to improve some of the Slack messages.
=> Improves formatting of some Slack messages

src/dispatch/incident/flows.py, src/dispatch/incident/messaging.py, src/dispatch/messaging.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/plugin.py
This PR adds a reminder for the incident commander to review the incident's information and to tag the incident when the incident is closed.
=> Asks the commander to review the incident's information on incident close

src/dispatch/static/dispatch/src/individual/api.js
Renames API param `termId` to `individualId`.
=> Fixes VueJS individual api param names

docs/cli.md, docs/contributing/environment.md
During local deploy of dispatch I found some typos in the commands in the documentation.
=> Fixed two typos in docs

src/dispatch/incident/flows.py, src/dispatch/plugins/dispatch_slack/actions.py
This cleans up the engage oncall flow and removes slack specific dependencies.
=> Refactoring and improving engage oncall messaging

src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/incident/store.js
Adds a tracking only checkbox, that creates a new incident in the "closed" state. Meaning no incident resources will be created for it.
=> Adds a tracking only checkbox and fixes commander rendering

src/dispatch/incident/flows.py
This PR fixes an issue where we were trying to run the `incident_active_status_flow` and unarchive the incident channel even for incident updates that did not have status changes.
=> Only reactivate incident when status goes from closed to active

src/dispatch/incident/flows.py, src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/service.py
This PR decouples incident channel creation from adding participants to it. Now we wait after the incident conversation has been created via the plugin and in the database to add participants to it.
Additionally, we will also retry when Slack API calls return `fatal_error`, which seems to be when Slack's performance is downgraded.
=> Makes incident conversation creation more robust

src/dispatch/plugins/dispatch_slack/config.py, src/dispatch/plugins/dispatch_slack/socket_mode.py
Let's allow the server to start even if `SLACK_SOCKET_MODE_APP_TOKEN` is not defined in the `.env` file. We will throw an error if it's not defined when the user runs `dispatch server slack`.
=> Sets default for Slack socket mode token

src/dispatch/database.py, src/dispatch/static/dispatch/src/components/AppDrawer.vue, src/dispatch/static/dispatch/src/incident/EditSheet.vue, src/dispatch/static/dispatch/src/incident/Table.vue, src/dispatch/static/dispatch/src/incident/store.js, src/dispatch/static/dispatch/src/router/config.js, src/dispatch/tag/models.py
Allows for true incident details to be displayed. i.e. when a user enters `/incidents/fooBar` the details sheet is displayed with data about fooBar.
Additionally, we now reload an incident data when that details sheet is displayed. This will allow us to limit the number of fields we need to return when listing incidents which should speed up the table as the number of incidents grows.
We may also want to transition other modals where we want the URL to reflect some sort of page state, e.g. /tasks/:id
Addresses #797
=> Allows incident details to be more flexible

src/dispatch/auth/views.py, src/dispatch/incident/views.py, src/dispatch/incident_priority/views.py, src/dispatch/incident_type/views.py, src/dispatch/plugin/views.py
This PR adds logic to restrict the creation and editing of incident types, priorities, and plugins to admins only.
=> Restricts certain configuration aspects to admins only

src/dispatch/messaging/strings.py
=> Removes extra blank line between title and description in incident update notifications

src/dispatch/incident/flows.py, src/dispatch/incident/messaging.py, src/dispatch/notification/views.py
This PR removes the is the incident's visibility open check before sending incident created and updated notifications. We are going to rely on the search filters in notifications to determine when notifications for incidents with restricted visibility need to be sent. Also, we now require Admin permissions to delete notifications to be consistent with notification creation and update.
=> Removes visibility open check before sending incident created and updated notifications

docs/configuration/plugins/configuring-jira.md, src/dispatch/plugins/dispatch_jira/config.py, src/dispatch/plugins/dispatch_jira/plugin.py
This PR refactors the Jira plugin to add support for cloud and server hosting types and to respect any provided incident type plugin metadata.
=> Jira plugin now supports cloud and server hosting type

src/dispatch/static/dispatch/src/document/DocumentSelect.vue, src/dispatch/static/dispatch/src/document/NewEditSheet.vue, src/dispatch/static/dispatch/src/document/store.js, src/dispatch/static/dispatch/src/incident_type/Table.vue, src/dispatch/static/dispatch/src/service/NewEditSheet.vue, src/dispatch/static/dispatch/src/service/ServiceSelect.vue, src/dispatch/static/dispatch/src/service/store.js
Adding the ability to create services and documents when creating/editing incident types.
=> Create services and documents from incident type

docs/installation.md
Looks like the `develop` branch is no more, and so this link is dead. Update to be `master` (will need to be changed again in the future if/when this project moves to `main`)
=> Update URL for example env

src/dispatch/static/dispatch/src/incident_type/NewEditSheet.vue
=> Disables nested validation observers when creating new or editing existing incident types

src/dispatch/incident/metrics.py, src/dispatch/incident/views.py, src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue, src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue, src/dispatch/static/dispatch/src/incident/IncidentForecastCard.vue, src/dispatch/static/dispatch/src/incident/api.js, src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue, src/dispatch/static/dispatch/src/search/utils.js, src/dispatch/tag/recommender.py, src/dispatch/tag/views.py
This PR improves our ability to forecast incidents and show historical accuracy. It attempts to get the best of both worlds by doing a forward-looking forecast to see how many incidents will be handled in the future, as well as "rolling historical forecasts". By restricting the data sets in the past we are able to re-forecast a historical month as if it were the last day of the previous month. 
We are then able to use that forecast to compare against the actual number of incidents in a given month. Combining these two strategies allows us to both observe the historical accuracy of our forecasting while using all currently available data for future forecasting.
Additionally, this PR adds the ability for us to forecast based on different subsets of data, e.g. how many incidents of type …
=> Allows for more flexible forecasting

src/dispatch/incident/models.py
This PR fixes a bug in the hybrid property for incident reporter that was causing the Web UI to not show the correct reporter if this had been updated.
=> Fixes hybrid property for incident reporter

src/dispatch/incident/flows.py, src/dispatch/incident/messaging.py, src/dispatch/tag/models.py
Allows the reporter/commander to be changed even when no conversation is associated.
=> Allows the reporter/commander to be changed 

src/dispatch/plugins/dispatch_slack/modals.py
Ensures we send confirmation and error messages when a user submits a modal.
=> Adding responses and default error message for incident modals 

src/dispatch/plugins/dispatch_slack/commands.py
If the command is run in an incident conversation, we return all incidents from the incident's project. If the command is run in a non-incident conversation, we return all incidents in all projects. We now also include the incident's project name in the response.
=> Improves list incidents Slack command

.github/workflows/python.yml
Fixes #1207 
1) Added black as a separate job
2) Made build dependent on lint so if lint fails, build job will be skipped
Thus, improved the use of GitHub actions in the repository
=> chore: improved GitHub actions

docs/installation.md
Without adding the project name it was giving a Traceback error - 
project name -> 
none is not an allowed value (type=type_error.none.not_allowed)
=> Fixed a command issue and added clarification

src/dispatch/plugins/dispatch_jira/plugin.py
This addresses an issue with Jira server where we may retrieve a user that doesn't have access to the given project (e.g. multiple users for a given email).
=> Only get users that have permission

utils/release_notes.py
Usage:
```
Usage: release_notes.py [OPTIONS]
Simple utility function to assist with generating release notes.
Options:
-n, --pull-request-number INTEGER
Pull request number from where to generate
the release notes.  [required]
--help                          Show this message and exit.
```
Example:
```
$ ./release_notes.py --pull-request-number 1430
* Bugfix/task creator by @mvilanova ([#1438](https://github.com/Netflix/dispatch/pull/1438))
* We don't send messages to the participant or channel if the incident is closed by @mvilanova ([#1437](https://github.com/Netflix/dispatch/pull/1437))
* Fixing faq and conversation reference by @kevgliss ([#1434](https://github.com/Netflix/dispatch/pull/1434))
* Fixing task source documents by @kevgliss …
```
=> Python script to assist with generating release notes

src/dispatch/auth/permissions.py
Unprocessable entity on any API request due to insufficient parameters supplied. Thus raising a pydantic exception which being in middleware will be handled as a 422 response
=> Unprocessable entity on any API request due to insufficient parameters

src/dispatch/document/scheduled.py
Fixes an issue where syncing document terms was accessing the wrong attribute.
=> Syncing document terms was accessing the wrong attribute

docs/installation.md
Following the existing instructions, I get the error `error: no such option: --project`
=> Update "First User" instructions in documentation

src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/incident/store.js
We've decided to remove the tracking-only checkbox in the reporting form, because it was creating confusion. If you wish to open an incident for tracking purposes, you can still go to the Dispatch UI and open an incident as closed, which is what the checkbox instructed Dispatch to do.
=> Removes tracking-only checkbox from incident reporting form

src/dispatch/incident/service.py
This PR will make individuals who open an incident as closed both the commander and liaison and will avoid paging the commander unnecessarily.
=> We do not resolve incident roles and page the commander for incidents opened as closed

src/dispatch/database/core.py
Adds a more readable repr for sqlalchemy objects. For example, printing a list of models will now print:
```
{'items': [<Incident #864>, <Incident #848>, <Incident #846>, <Incident #841>, <Incident #822>, <Incident #813>, <Incident #812>, <Incident #791>, <Incident #788>, <Incident #787>], 'itemsPerPage': 10, 'page': 1, 'total': 575}
```
Additionally, it exposes a ` __repr_attrs__` property to all sqlalchemy models such that you can further specify other attributes that should be included in a model's repr.
=> Adds better repr for our sqlalchemy objects

src/dispatch/database/revisions/tenant/versions/2021-08-09_b73416df5744.py
With incident roles we now support incident priorities, to ensure that any migration behaves the same way as the current mappings we need to match on all existing priorities.
=> Ensures new incident roles match all priorities

src/dispatch/database/revisions/tenant/versions/2021-08-09_b73416df5744.py
The name of the table is singular `incident_role_incident_priority`, not plural `priorities`. The migration fails without this fix. Check the names of the variables and table for the `incident_role_incident_type` table for a working example.
=> Fix table name for incident_role_incident_priority in db migration

src/dispatch/cli.py, src/dispatch/config.py, src/dispatch/main.py, src/dispatch/static/dispatch/package.json
Hello,
Currently, running `dispatch server develop` fails on windows because of the static file paths.
Also the front-end will never be served  because the env var `STATIC_DIR` has a default.
=> Support windows file path & env vars for CLI serve command

src/dispatch/database/service.py, src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue
This PR modifies the restricted incident filter applied when querying all incidents to allow all roles except `member` to see restricted incidents.
=> Allows all roles except member to see restricted incidents

src/dispatch/static/dispatch/vue.config.js
This change seem to solve the following proxying issue:
```
Proxy error: Could not proxy request /api/v1/organizations?itemsPerPage=50&sortBy[]=name&descending[]=false from localhost:8080 to http://localhost:8000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
=> Replaces localhost with 127.0.0.1 in devServer vue.config.js

src/dispatch/incident/models.py, src/dispatch/static/dispatch/src/incident/ParticipantsTab.vue, src/dispatch/static/dispatch/src/incident/TimelineTab.vue, src/dispatch/static/dispatch/src/incident/WorkflowInstanceTab.vue
Changes to pydantic models in https://github.com/Netflix/dispatch/pull/1828/ broke our ability to load the contents of the resources, participants, timeline, and workflow incident tabs. This PR reverts to using the IncidentRead pydantic model.
=> Reverts to IncidentRead in IncidentPagination Pydantic model

src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
This PR attempts to address the following error:
```
TypeError: Cannot read properties of null (reading 'name')
at n/a(webpack:///src/incident/ReportSubmissionCard.vue:155:0)
at n/a(webpack:///src/incident/ReportSubmissionCard.vue:181:9)
```
=> Initializes data properties to avoid typerror exceptions in report submission card

src/dispatch/static/dispatch/src/data/query/QuerySelect.vue, src/dispatch/static/dispatch/src/data/query/store.js, src/dispatch/static/dispatch/src/data/source/SourceSelect.vue, src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatCombobox.vue, src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatSelect.vue, src/dispatch/static/dispatch/src/data/source/environment/EnvironmentCombobox.vue, src/dispatch/static/dispatch/src/data/source/environment/EnvironmentSelect.vue, src/dispatch/static/dispatch/src/data/source/status/StatusCombobox.vue, src/dispatch/static/dispatch/src/data/source/status/StatusSelect.vue, src/dispatch/static/dispatch/src/data/source/transport/TransportCombobox.vue, src/dispatch/static/dispatch/src/data/source/transport/TransportSelect.vue, src/dispatch/static/dispatch/src/data/source/type/TypeCombobox.vue, src/dispatch/static/dispatch/src/data/source/type/TypeSelect.vue, src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue, src/dispatch/static/dispatch/src/incident/IncidentCombobox.vue, src/dispatch/static/dispatch/src/incident/IncidentFilterCombobox.vue, src/dispatch/static/dispatch/src/incident/IncidentSelect.vue, src/dispatch/static/dispatch/src/incident_cost_type/IncidentCostTypeCombobox.vue, src/dispatch/static/dispatch/src/incident_type/IncidentTypeCombobox.vue, src/dispatch/static/dispatch/src/individual/IndividualCombobox.vue, src/dispatch/static/dispatch/src/individual/IndividualSelect.vue, src/dispatch/static/dispatch/src/project/ProjectCombobox.vue, src/dispatch/static/dispatch/src/project/ProjectSelect.vue, src/dispatch/static/dispatch/src/search/SearchFilterCombobox.vue, src/dispatch/static/dispatch/src/service/ServiceSelect.vue, src/dispatch/static/dispatch/src/service/ServiceSelectNew.vue, src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue, src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
In some cases (typically with cross-project entities) there can be multiple entries with the same name. We denote the ID of the value instead of it's name such that these "duplicates" are correctly displayed in the dropdown.
=> Fixes issue with comboboxes not displaying multiple items with the same name.

src/dispatch/tag/models.py
This change allows for more accurate searching for tag names. Since most tags are single words, we use the simple dictionary to capture the entire name (instead of breaking up lexemes like 'hack' & 'ing'. The search also enables better control when exact matching is required by wrapping your query in quotes. for example:
names: hacking, thehacking, thebiggesthack
lexemes: "hack"
query: hacking -> matches all
query: hack -> matches all
query: "hacking" -> matches hacking
=> Uses the simple search dictionary for fulltext search

docs/admin-guide/administration/server.md
I had to browse through the code to understand the possible values of Log levels. Apparently the log levels are in Upper case, and the default value is shown in lowercase, which misled me into believing that all log levels should be in lower case.
Hopefully, this change will be meaningful for other readers.
=> Update Admin Documentation on Environment variables

src/dispatch/incident_cost/scheduled.py, src/dispatch/static/dispatch/src/incident/IncidentPriorityBarChartCard.vue
We currently update the cost of _all_ incidents regardless of their status. This PR introduces changes, so Dispatch only updates the cost of active and stable incidents to avoid impacting older cost metrics when changes to average cost per employee or number of annual business hours are made.
=> Only update the cost of active and stable incidents

src/dispatch/incident/messaging.py
This PR addresses the second issue reported in https://github.com/Netflix/dispatch/issues/2163
=> Only use markdown for new incident participant message when participant weblink exists

src/dispatch/database/revisions/tenant/versions/2022-05-23_748744207122.py
Run `dispatch database upgrade` to fix incident document, review document, and tactical and notifications group foreign keys in the incident table.
=> Fixes resource foreign keys in incident table

src/dispatch/plugins/dispatch_slack/commands.py
Prior to this, Slack was assinging a random 4-digit action_id that was causing the resolve and re-open buttons for a task to be a no-op.
Adding this routes the slack action to the right block_action_function (update_task_status).
Tested on my end.
=> Attribute action_id missing in task actions button.

src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
We don't (yet) present incident_costs attribute/field in Slack's update_incident modal, causing the update function to incorrectly (re)set it to zero.
=> Copy over incident_costs, terms & duplicates before updating incident from Slack

requirements-base.in, requirements-base.txt, src/dispatch/plugins/dispatch_slack/decorators.py, src/dispatch/plugins/dispatch_slack/menus.py, src/dispatch/plugins/dispatch_slack/views.py
Add uvloop support to run the async event loop; uvicorn will pick this over asyncio, if available. Not sure about others, but In my setup (ubuntu VM), not having uvloop was resulting in 8/10 calls failing (some like /dispatch-update-incident failed 10/10) to Slack's API with the 'expired_trigger_id' error. I still see that error (w/uvloop), but it is more like 1/10. Also, this is an configurable option: "--loop [auto|asyncio|uvloop]    Event loop implementation.  [default: auto]"
Also, including the commit from earlier today which fixes slack_menu returning empty tag list from non-incident channels. Not sure how that was missing in the master branch although. 
Some minor str changes.
=> slack_menu empty tag list fix; uvloop support.

src/dispatch/evergreen/scheduled.py, src/dispatch/feedback/messaging.py, src/dispatch/incident/messaging.py, src/dispatch/notification/service.py, src/dispatch/plugins/dispatch_slack/config.py, src/dispatch/report/messaging.py, src/dispatch/task/flows.py
Gmail is consistency throwing below exception during .send(). GCP "golden signals" for the API look fine. Also, no similar issues with other gsuite calls like drive and groups. 
`ERROR:Error/Exception in sending Tactical Report email to ...... RetryError[<Future at 0x7f613d72ce80 state=finished raised KeyError>]  `
Weird thing is, the emails are still being sent. Actually, sent three times (tenacity retry_count of 3) to a domain account; one email to a regular gmail account (despite making three calls and same end error). 
Without the wrap, incident creation fails at the send_inc_notifs stage. Not sure if anyone else is experiencing this, but if they do,  this should help in the interim. 
I will continue to dig deeper.
=> Wrap gmail.send in try/except due to tenacity.RetryError

src/dispatch/logging.py
Hello,
thank you for dispatch, looks great and super useful!
While testing/deploying I came across an inconsistency between cli's `--log-level` and `LOG_LEVEL` in env/config. Namely the latter can be only uppercase while the former is lower case. What do you think of the attached commit ?
thank you!
=> Always upper log_level before logging config

src/dispatch/incident/flows.py, src/dispatch/plugins/dispatch_google/drive/drive.py
During create_flow, if the reporting template doesn't exist, we create a new one, but immediately try to access the non-existent `description` attr during update(), which throws an exception. This fixes it.
Added code to create a new tracking sheet if template is not in config, with update() moved like above.
Added if/else flow based on the mimeType.
Tested my changes.
=> Fixes doc creation issue if template is None

src/dispatch/incident/flows.py
Fixes an issue introduced in https://github.com/Netflix/dispatch/pull/2443. Ensures we always have a description for each collaboration document.
=> Fixes issue during the creation of incident collaboration documents

src/dispatch/case/views.py, src/dispatch/data/alert/views.py, src/dispatch/data/query/views.py, src/dispatch/data/source/data_format/views.py, src/dispatch/data/source/environment/views.py, src/dispatch/data/source/status/views.py, src/dispatch/data/source/transport/views.py, src/dispatch/data/source/type/views.py, src/dispatch/data/source/views.py, src/dispatch/definition/views.py, src/dispatch/document/views.py, src/dispatch/feedback/views.py, src/dispatch/incident/views.py, src/dispatch/incident_cost/views.py, src/dispatch/incident_cost_type/views.py, src/dispatch/individual/views.py, src/dispatch/notification/views.py, src/dispatch/plugin/views.py, src/dispatch/project/views.py, src/dispatch/search_filter/views.py, src/dispatch/service/views.py, src/dispatch/tag/views.py, src/dispatch/tag_type/views.py, src/dispatch/task/views.py, src/dispatch/team/views.py, src/dispatch/term/views.py, src/dispatch/workflow/views.py
In FastAPI versions 0.80.0 or newer, the server now raises an internal server error if you are using `response_model` with some type that doesn't include `None`, but the function is returning `None`. More details [here](https://github.com/tiangolo/fastapi/releases/tag/0.80.0).
This PR sets `response_model` for all delete endpoints to `None` to prevent errors, and fixes some typos, docstrings, and response messages.
=> Sets response model to None for all delete endpoints to address breaking changes in FastAPI v0.80.0

src/dispatch/case/flows.py, src/dispatch/group/flows.py, src/dispatch/plugins/dispatch_google/drive/drive.py, src/dispatch/plugins/dispatch_google/drive/plugin.py, src/dispatch/storage/enums.py, src/dispatch/storage/flows.py, src/dispatch/ticket/flows.py
This PR adds support for creating an incident when a case is moved to the escalated status if the case's type is mapped to an incident type and the case is not linked to any incidents already. The case assignee becomes the incident's reporter and the members of the incident's tactical group are given permission to access the case's storage folder and its contents.
=> Creates an incident when a case is moved to the escalated status

docs/admin-guide/administration/server.md, setup.py, src/dispatch/config.py, src/dispatch/plugins/dispatch_core/plugin.py
Hello @mvilanova,
This is a first attempt at authenticating users via request headers, please let me know what you think!
=> Adds header-based auth plugin

src/dispatch/static/dispatch/src/case/priority/Table.vue, src/dispatch/static/dispatch/src/case/severity/Table.vue, src/dispatch/static/dispatch/src/case/type/Table.vue, src/dispatch/static/dispatch/src/data/source/dataFormat/Table.vue, src/dispatch/static/dispatch/src/data/source/environment/Table.vue, src/dispatch/static/dispatch/src/data/source/status/Table.vue, src/dispatch/static/dispatch/src/data/source/transport/Table.vue, src/dispatch/static/dispatch/src/data/source/type/Table.vue, src/dispatch/static/dispatch/src/definition/Table.vue, src/dispatch/static/dispatch/src/document/reference/ReferenceTable.vue, src/dispatch/static/dispatch/src/document/runbook/RunbookTable.vue, src/dispatch/static/dispatch/src/document/template/TemplateTable.vue, src/dispatch/static/dispatch/src/incident_cost_type/Table.vue, src/dispatch/static/dispatch/src/incident_priority/Table.vue, src/dispatch/static/dispatch/src/incident_role/Table.vue, src/dispatch/static/dispatch/src/incident_type/Table.vue, src/dispatch/static/dispatch/src/individual/Table.vue, src/dispatch/static/dispatch/src/notification/Table.vue, src/dispatch/static/dispatch/src/plugin/Table.vue, src/dispatch/static/dispatch/src/service/Table.vue, src/dispatch/static/dispatch/src/tag/Table.vue, src/dispatch/static/dispatch/src/tag_type/Table.vue, src/dispatch/static/dispatch/src/team/Table.vue, src/dispatch/static/dispatch/src/workflow/Table.vue
On smaller screen sizes the settings breadcrumbs will collapse when there is still whitespace available. This change will prioritize those UI elements over whitespace.
=> Allows setting breadcrumbs to utilize the whole width before collapsing

src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseEscalatedClosedAverageTimeCard.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseNewClosedAverageTimeCard.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseNewTriageAverageTimeCard.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseSeverityBarChartCard.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseTriageEscalatedAverageTimeCard.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseTypeBarChartCard.vue
This PR adds the following widgets and charts to the cases dashboard:
Widgets
* Number of cases triaged
* Number of cases escalated
Charts
* Number of case types by month
* Number of case severities by month
* New to triage average time
* Triage to escalated average time
* Escalated to closed average time
* New to closed average time
=> Cases Dashboard

src/dispatch/scheduler.py
This ensures that each scheduled task is not run serially. This should increase the reliability of the scheduled tasks, guaranteeing that long-running tasks do not cause other tasks to miss their execution windows.
=> Runs every scheduled job in it's own thread.

src/dispatch/auth/models.py, src/dispatch/case/severity/models.py, src/dispatch/data/alert/models.py, src/dispatch/data/query/models.py, src/dispatch/data/source/data_format/models.py, src/dispatch/data/source/environment/models.py, src/dispatch/data/source/models.py, src/dispatch/data/source/status/models.py, src/dispatch/data/source/transport/models.py, src/dispatch/data/source/type/models.py, src/dispatch/definition/models.py, src/dispatch/document/models.py, src/dispatch/feedback/models.py, src/dispatch/notification/models.py, src/dispatch/service/models.py, src/dispatch/tag_type/models.py, src/dispatch/task/models.py, src/dispatch/term/models.py
This change unifies search expectations across models; we had this on some models but not others. Essentially, by using the `simple` dictionary, we are not attempting to filter out stop words from our search terms (e.g. the, from, to). 
This filtering was confusing to users, and we could run into situations where a resource (e.g. incident_type) was in the form of a stop, but we would not be able to filter for that resource due to the query filtering. 
This change simplifies the search expectation to; if a word is in the column that the search returns column. 
Additional context:
https://forestry.io/blog/full-text-searching-with-postgres/
=> Uses the 'simple' dictionary to provide better search consistancy

docs/admin-guide/administration/cli.md, docs/admin-guide/administration/plugins/README.md
I've spent a considerable amount of time trying to debug why the plugins wouldn't show up in the `Add Plugin` form in the dashboard. Maybe it's missing because most people start with the prepopulated DB? If so, wouldn't it be better to add some of this to the init db script?
=> Add hint to using CLI to install plugins

src/dispatch/auth/permissions.py, src/dispatch/incident/views.py, src/dispatch/plugins/dispatch_slack/actions.py, src/dispatch/static/dispatch/src/incident/store.js
This PR adds support for check incident visibility before allowing individuals to join or subscribe to an incident. This is useful in situations where the incident was opened with open visibility and later on changed to restricted.
=> Check incident visibility before allowing individuals to join or subscribe to an incident

src/dispatch/cli.py
When fulltext search triggers already exist, syncing new triggers can be problematic as the functions and expressions are tightly coupled with the columns they monitor. This change removes the automatic syncing functionality to make migrations more reliable. From now on if you add a new column that requires fulltext search functionality, you will have to manually sync the trigger in the migration file itself. See:
https://sqlalchemy-searchable.readthedocs.io/en/latest/alembic_migrations.html#sqlalchemy_searchable.sync_trigger
=> Don't attempt to sync triggers automatically on database upgrade

src/dispatch/models.py
We don't validate any other "weblink" properties, so this removes an edge case.
=> Removed resource weblink resource validation as web link is not necessarily a URL.

src/dispatch/static/dispatch/src/document/reference/store.js
Fixes an issue where FAQs were being created without the correct resource type and thus never associated with incidents.
=> Adds correct resource type when FAQs are created.

src/dispatch/plugins/dispatch_slack/messaging.py
Related to #2695. Missed another reference.
=> Fixes issue with severity and report confirmation message

src/dispatch/messaging/strings.py
Removes reference to incident conversation, as it does not make sense in the Slack ephemeral message sent to the participant in the incident conversation and assumes the incident will have a conversation.
=> Improves incident participant welcome message description

src/dispatch/individual/service.py, src/dispatch/plugin/models.py, src/dispatch/plugins/base/v1.py, src/dispatch/plugins/dispatch_core/plugin.py
when an incident is created, reporter's name is reset to their "email".
reasons:
1. project_id is not provided to `get` method of the contact plugin
2. `individual.service` checks for a `fullname` field while `name` is actual field of the IndividualContact table
=> individual name is wrongly resolved

src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/router/index.js
Hi, All!
I noticed that, at least, in case of basic auth, the token stored in the storage is not checked for. Therefore, upon refresh user needs to login again.
I suggest some potential change that fixes this. I'm a newcomer to dispatch, so I expect I will learn something new soon :)
Look forward to your feedback!
Cheers,
Victor
=> Checks for auth token on app refresh

src/dispatch/plugins/dispatch_slack/bolt.py, src/dispatch/plugins/dispatch_slack/decorators.py, src/dispatch/plugins/dispatch_slack/endpoints.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/plugins/dispatch_slack/middleware.py, src/dispatch/plugins/dispatch_slack/service.py
`resolve_context_from_conversation` sometimes returns `None` if no `conversation` is found (command is ran from #general or a DM) and results in:
```bash
ERROR:Failed to run a middleware function (error: cannot unpack non-iterable NoneType object)
```
`NamedTuple` seemed like a nice solve here.
`@handle_lazy_error` results in:
```bash
DEBUG:Failed to run a lazy listener function handle_assign_role_submission_event:/Users/wshel/Projects/dispatch/src/dispatch/plugins/dispatch_slack/decorators.py:handle:55
ERROR:handle_assign_role_submission_event: There was an error!:/Users/wshel/Projects/dispatch/src/dispatch/plugins/dispatch_slack/decorators.py:handle:56
Traceback (most recent call last):
File "/Users/wshel/Projects/dispatch/src/dispatch/plugins/dispatch_slack/decorators.py", line 53, in …
```
=> add lazy error decorator, resolve tuple unpack exception, and minor type changes

src/dispatch/plugins/dispatch_slack/middleware.py, src/dispatch/plugins/dispatch_slack/service.py
This resolves a bug where non-incident commands incorrectly reported that the bot was not present in private channels. Consolidates `get_public/private_conversations_by_user_id_async` into a single function that accepts a `type` param and generates a unique cache key for public / private channels, which is the root cause of the bug.
=> consolidate get_conversations service method and resolve cache issue

src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/plugins/dispatch_slack/models.py, src/dispatch/task/service.py
- Support tasks created in the front-end (which don't have a `resource_id`)
- Automatically update the status within the modal and live update the modal
- Move modal builder to a draw function
- Create small open and close function in `task_service`
=> add task button handler and modal draw function, support front-end tasks

src/dispatch/incident/flows.py
Fix error when there is no conversation plugin enabled, but storage plugin is enabled.
```
ERROR:'NoneType' object has no attribute 'channel_id':/usr/local/lib/python3.9/site-packages/dispatch/decorators.py:wrapper:92
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/dispatch/decorators.py", line 85, in wrapper
result = func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 1240, in incident_update_flow
status_flow_dispatcher(
File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 1180, in status_flow_dispatcher
incident_stable_status_flow(incident=incident, db_session=db_session)
File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 1016, in …
```
=> Fix none error when conversation plugin is not enabled

src/dispatch/plugins/dispatch_slack/decorators.py
Incorrectly attempting to send `after_hours_notification` for new participants, `channel_join` should be filtered in `exclude` statement within `message_dispatcher` decorator. For example:
```python
@message_dispatcher.add(
exclude={"subtype": ["channel_join", "group_join"]}
)
```
This is ignored, which results in:
```
'NoneType' object has no attribute 'after_hours_notification'
```
```
DEBUG:Skipping a dispatched function handle_participant_role_activity:/Users/wshel/Projects/dispatch/src/dispatch/plugins/dispatch_slack/decorators.py:dispatch:37
DEBUG:Skipping a dispatched function handle_after_hours_message:/Users/wshel/Projects/dispatch/src/dispatch/plugins/dispatch_slack/decorators.py:dispatch:37
```
=> fix exclude logic in message dispatch decorator

src/dispatch/plugins/dispatch_slack/endpoints.py, src/dispatch/plugins/dispatch_slack/handler.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/plugins/dispatch_slack/middleware.py, src/dispatch/plugins/dispatch_slack/workflow.py
We still receive occasional command timeouts after running Slash commands or handling message events. 
This PR leverages Starlette background task to *instantly* return a `200` `OK` to Slack upon receipt of a `/command` or `/event` interactivity payload. This change ensures that the first thing we do is acknowledge the request and aren't waiting on Bolt at all.
In my tests, I discovered that calling `ack()` at the beginning of our middleware function does not *actually* send a `200` back to Slack *at that point*. The way bolt works, it doesn't matter when you call `ack()`, as long you call it at the beginning of your listener function ([like this](https://github.com/Netflix/dispatch/pull/2907/files#diff-d2495d41fbf8f5c5500a410dc9fdcbcb271af34de0a447a84c0ec7b7a200b67bR444)). If you call it …
=> instantly acknowledge /command and /event requests from slack

src/dispatch/plugins/dispatch_slack/bolt.py, src/dispatch/plugins/dispatch_slack/decorators.py, src/dispatch/plugins/dispatch_slack/messaging.py
Before we sent an unexpected error message.
=> Add custom error message for expired trigger ids

src/dispatch/plugins/dispatch_github/plugin.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
[docs](https://docs.github.com/en/github-ae@latest/admin/identity-and-access-management/managing-iam-for-your-enterprise/username-considerations-for-external-authentication#:~:text=Usernames%20for%20user%20accounts%20on%20GitHub%20AE%20can%20only%20contain%20alphanumeric%20characters%20and%20dashes%20(%2D).)
✅ with dashes
✅ without dashes
=> github repo and org/user can have dashes

src/dispatch/database/service.py, src/dispatch/static/dispatch/src/incident/DetailsTab.vue, src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue, src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
With the switch to the minimalist tag model, this is no longer included. We should consider making tag names exclusive across projects if we expect a user to be able to determine which tag they wish to filter on.
=> Fixes issue where tags list expected a project field

src/dispatch/incident/service.py
Generally, an incident is moved to stable when the risk has been mitigated or contained and thus the priority or urgency can be lowered. This PR adds some logic to set the priority to the default in the project, which unless changed, it would be Low.
=> Resets incident priority to default priority when incident is marked as stable

src/dispatch/incident/flows.py
Support Incident date in storage plugins to make the document event richer.  This would enable plugins to calculate recovery time ( Reported-stable).
Document plugins will now support the following in the update.
```
{{incident_stable_time}}
{{incident_reported_time}}
```
=> Support incident date in storage

src/dispatch/incident/flows.py
This PR fixes a `TypeError: Object of type datetime is not JSON serializable` exception when the `reported_at` and `stable_at` timestamps were getting passed to the Google document plugin as datetime objects.
cc @Cinojose
=> Converts timestamps to strings before passing them to the document plugin

src/dispatch/static/dispatch/src/case/EditSheet.vue
Same bug as https://github.com/Netflix/dispatch/pull/3068/files -- If you switch the `Signal` tab very quick after you open the `CaseEditSheet` (before `selected.signal_instances` has been fetched), the Signal data will say there's no data/signals but there is.
=> wait for selected signal data for rendering signal tab

src/dispatch/cli.py
If you run `vms database drop` when the database is not existing, it results in `sqlalchemy.exc.ProgrammingError`. This is just a minor fix to give a better CLI experience.
=> CLI drop database modified to address in case the database doesn't exist

src/dispatch/static/dispatch/src/signal/TableInstance.vue
@kevgliss removing for now, will explore popover that we can reuse across the app, and here.
=> remove entities from signal instance table

.gitignore
Since it's auto-generated we can probably add it to `.gitignore`, it only generates type definitions, and we don't really use typescript anyway.
=> move components.d.ts to .gitignore

src/dispatch/plugins/dispatch_slack/bolt.py
Error messages that occurred in a thread context (for example, clicking the `Snooze` button) went to the main channel, which is a poor user experience. This PR sends the error message to the thread as an ephemeral message.
=> add support for errors in threads

src/dispatch/plugins/dispatch_slack/case/interactive.py
Early return prevents general exception message from being sent in addition to the user friendly error modal. Also, improve the error message in the modal.
=> improve no entity error message and return early after modal open 

src/dispatch/static/dispatch/src/components/AppDrawer.vue
=> Fixes issue with mini width when submenu is displayed

src/dispatch/static/dispatch/src/case/BulkEditSheet.vue, src/dispatch/static/dispatch/src/case/ClosedDialog.vue, src/dispatch/static/dispatch/src/case/store.js
=> Adding bulk closed resolution

src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/signal/service.py
The idea here is that if no entities are provided we will snooze the entire variant for the specified amount of time.
=> Making entities optional for snoozing

src/dispatch/plugins/dispatch_slack/case/interactive.py
Tested across all relative date options
=> Fix relative (days) time option for snooze filter creation in Slack plugin

src/dispatch/case/flows.py, src/dispatch/incident/flows.py, src/dispatch/individual/service.py, src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/signal/flows.py
Resources are still created successfully on case escalation
=> Conditional creation of case resources for perf improvement on signal ingest

src/dispatch/cli.py, src/dispatch/signal/flows.py, src/dispatch/signal/scheduled.py, src/dispatch/signal/service.py
This PR introduces a blocking thread-safe FIFO queue in the signal ingestion pipeline. This ensures signals are processed in the order they were received and prevents race conditions where a signal instance can override a shared value (e.g. case associations). The queue has a max size of 500 that is also used to limit the number of instances retrieved by the query in `process_signals`. We also create a `scoped_session` for each run of the scheduler.
A boundary of `.filter(SignalInstance.created_at >= one_hour_ago)` was added to the ingestion query to prevent cases where we are unable to keep up for an hour, which should never happen, and if it does is an acceptable scenario to prevent performance issues and outages.
Caching logic was introduced in `_should_update_signal_message` to …
=> Optimize signal ingestion pipeline and create perf-test cli util

src/dispatch/static/dispatch/src/tag/DeleteDialog.vue, src/dispatch/static/dispatch/src/tag/List.vue, src/dispatch/static/dispatch/src/tag/NewEditSheet.vue, src/dispatch/static/dispatch/src/tag/Table.vue, src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue, src/dispatch/static/dispatch/src/tag/TagSummaryTable.vue
Disabling tag recommendations in TagFilterAutoComplete UI component as they don't currently support loading more tags.
=> Disables tag recommendations in TagFilterAutoComplete UI component

src/dispatch/static/dispatch/package.json, src/dispatch/static/dispatch/vite.config.js
Resolves:
```
Expected a JavaScript module script but the server responded with a MIME type of "text/html" in Vue with Vite
```
https://vitejs.dev/guide/build.html#public-base-path
https://axellarsson.com/blog/expected-javascript-module-script-server-response-mimetype-text-html/
=> set explicit build dir in Vite to resolve `Expected a JavaScript module on rebuild` error

docs/docs/administration/settings/messaging.mdx, src/dispatch/messaging/email/utils.py, src/dispatch/plugins/dispatch_google/gmail/plugin.py
There is a way to have customizable templates for dispatch today, by mounting a volume with a customized templates dir as part of the docker compose:
```
web:
image: dispatch-local
...
volumes:
- "../dispatch-templates/messaging-email-templates:/usr/local/lib/python3.11/site-packages/dispatch/messaging/email/templates"
```
This approach does allow to customize the templates "deployment"-wide.
In this PR I suggest a small extension of this functionality. You can create a folder per project (identified by project id):
```
dispatch/messaging/email/templates/project_id/<project_id>/base.mjml
```
This will be used at the first place if exists, otherwise will gracefully fall back to the default template like "/templates/base.mjml".
I was a bit afraid to use "slug" of the project name, because …
=> Allow customizing notification templates per project

src/dispatch/decorators.py
I'm not exactly sure which part of the change was the issue, but it resulted in an explosion of database connections, ultimately exhausting the database. It likely has to do with the context manager not exiting as expected and the session not being closed. 
I've reverted this because I don't think it's currently required, but was opportunistic in nature (it was included in a PR with other unrelated optimizations).
=> Rolls back session changes in #3365

docs/docs/administration/contributing/environment.mdx
Dispatch uses the `|` operator and requires python 3.10+.
=> Updates documentation about prerequisites

.eslintrc.json, .prettierrc, src/dispatch/static/dispatch/src/search/Table.vue
=> Uses colors to visually differentiate between used and unused filters in search filter table

src/dispatch/cli.py
Commenting the function import was not effective at stopping the scheduler from running the job. Uncommenting import and using the `--exclude` scheduler option instead.
=> Re-imports the incident auto tagger function

src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue, tests/static/e2e/pages/report-incident-page.ts, tests/static/e2e/report-submission.spec.ts
Adds the following query params for the incident intake form:
- title
- description
- tag (tag name)
Example: <hostname>:<port>/default/incidents/report?project=default&title=ExampleTitle&description=ExampleDescription&tag=ExampleTag
=> Allows pre-population of the incident title, description, and tags in the incident intake form by including them in the URL path.

src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue, src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
Previously, the dashboard filtered out all duplicate incidents and cases.
This change updates the dashboard filters to include items marked as duplicates as long as the originals are not part of the same returned data set. This allows new/reopened issues to be reflected on the dashboard metrics but still prevents double counting.
=> Updates dashboard filters

src/dispatch/plugins/dispatch_slack/enums.py, src/dispatch/plugins/dispatch_slack/service.py
=> Revert "Updates Dispatch Conversation URLs to reflect complete workspace URL"

src/dispatch/static/dispatch/src/organization/OrganizationMemberNewEdit.vue
Fixes bug introduced in https://github.com/Netflix/dispatch/pull/3397. The `disabled` prop is of type Boolean: https://vuetifyjs.com/en/api/v-text-field/#props-disabled.
=> Fixes bug in Organization Member New Edit UI component

src/dispatch/plugins/dispatch_slack/case/interactive.py
In the event a Dispatch admin approves an engagement we should not update the initial message with the user who clicked the button, but rather the original engaged user.
=> the engaged_user should be used in the updated message

src/dispatch/plugins/dispatch_slack/case/messages.py
Case pri color appears to default to caps when setting in UI, somehow mine was lowered, and it appears to be the same in production. Standardizing to lower in the `create_case_message`.
=> lower all case priorities to standardize

docker/Dockerfile, src/dispatch/static/dispatch/src/app/store.js, src/dispatch/static/dispatch/src/auth/store.js, src/dispatch/static/dispatch/src/components/AppToolbar.vue, src/dispatch/static/dispatch/src/filters.js
This shows the version information (i.e., the latest commit hash) in the help dialog. If none is available, the row is skipped. Clicking on the hash shows a snackbar with the full hash and commit message. 
Note: requires pushing the commit hash and message to the environment during the build process.
=> Shows version in help dialog and toast for full version info

src/dispatch/database/service.py
Determined that the Jira plug-in was adding the name in the search_vector as "-xxxx" instead of just "xxxx", causing the search to not find incidents when users search just for "xxxx"
=> Allows searching by incident number for Jira-created incident names

src/dispatch/search/views.py
This fixes an issue where global search wouldn't return restricted visibility incidents for which the user was a member.
=> Fixing issue where global search wouldn't return restricted visibility incidents

src/dispatch/static/dispatch/src/components/AppToolbar.vue, src/dispatch/static/dispatch/src/router/config.js, src/dispatch/static/dispatch/src/search/ResultList.vue, src/dispatch/static/dispatch/src/search/store.js
This PR adds the global search query to the URL, providing a way to copy & paste the search query, and allowing direct access to search results via URL. For instance, `https://dispatch.com/org/search/results?q=281` will show the search results for the query "281".
=> Allows users to conduct global search via the URL

src/dispatch/conversation/service.py, src/dispatch/plugins/dispatch_slack/case/enums.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/middleware.py
This PR adds a triage button that is only shown then the case is in the "New" state. Click it simple moves the case to "triage" state. 
Additionally, this PR adds support for processing case messages (this wasn't working before apparently) by modifying the way we look up conversation context to allow for specifying thread_id together with conversation_id. 
With these case messages now being properly processed, a message listener moves the case to triage on the first non-bot message. 
Dispatch won't currently allow for participant conversation and the case to stay in the "New state". I'm not sure if there is a use case for such a scenario.
=> Adds triage button

src/dispatch/decorators.py
I believe our main issue is because we are using `session.close()` instead of `session.remove()` and because each scheduled run is in it own thread we should be using `scoped_session` as well. This seems to work fine in my tests, but will be hard to tell for sure until we do a deployment with this code to see if it actually resolves our connection issues.
https://docs.sqlalchemy.org/en/13/orm/contextual.html#contextual-thread-local-sessions
=> Uses a scoped session for scheduler objects.

src/dispatch/signal/service.py
This allows a signal definition referenced directly by its external id. Allows for direct interaction with other integration. 
We already allow signal instances to reference signal definitions by their external id. This just extends that logic to the API as well as the signal instance post body.
=> Allow a signal definition to be referenced by it's external id

src/dispatch/static/dispatch/src/auth/store.js
Fix to move avatar URL template to .env file for easy configuration by organization.
=> Moving avatar URL template to configuration file

src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/case/ResourcesTab.vue, src/dispatch/static/dispatch/src/case/store.js
Adds ui elements so we can find the case conversation.
=> Bugfix/conversation UI

src/dispatch/case/models.py, src/dispatch/case/views.py
This was dropped from a previous PR by accident. It allows for the full data object, specifically which signals were associated with the case.
=> Adds ability to expand case attributes via the api

src/dispatch/conversation/flows.py
When creating the incident channel in Slack, this PR adds a bookmark to the incident in the Dispatch UI. It won't add the bookmark if the project is using the default dispatch ticket plugin since this will already be added as the "Ticket" bookmark.
=> Add the Dispatch UI bookmark to incident channel

src/dispatch/plugins/dispatch_slack/case/interactive.py
This PR replaces all instances of deprecated `incident_flows.add_participants_to_conversation()` with `conversation_flows.add_participants()` to fix adding participants to an incident resulting from an escalated case and allowing them to join it.
=> Fixes issue with adding a participant to an incident conversation from an escalated case

src/dispatch/static/dispatch/src/case/EscalateDialog.vue
This PR fixes an issue with the case escalation dialog where case type was being used in the incident type field rather than the incident type mapped to the case type.
=> Fixes issue with case escalation dialog

src/dispatch/conversation/flows.py
Fixes the Slack Dispatch UI bookmark to use the incident name in the URL instead of the default resource locator.
=> Correcting link for Dispatch UI Slack bookmark

src/dispatch/plugins/dispatch_pagerduty/plugin.py, src/dispatch/plugins/dispatch_pagerduty/service.py
This PR reverts some of the unneeded changes to the PagerDuty plugin which caused the `get()` to return a `dict` instead of the expected oncall email as a `str`.
=> Reverts unneeded changes to PagerDuty plugin

src/dispatch/feedback/service/scheduled.py, src/dispatch/service/service.py
Fixes bug where the oncall end-of-shift feedback was sending multiple times since the db query wasn't being filter by project.
=> Filters health metrics for given project

src/dispatch/plugins/dispatch_slack/service.py
We really shouldn't be attempting to silence specific API errors in this function as it doesn't know if it's safe to discard them. Instead, we should propagate to the caller and let them decide how to handle the error. Afaict all the callers that care about `CHANNEL_NOT_FOUND`, `USER_NOT_IN_CHANNEL`, and `USERS_NOT_FOUND` already handle those errors themselves.
=> Rework the way slack api errors are propagated (to the caller)

src/dispatch/api.py, src/dispatch/feedback/service/models.py, src/dispatch/feedback/service/reminder/service.py, src/dispatch/feedback/service/scheduled.py, src/dispatch/feedback/service/views.py, src/dispatch/plugins/dispatch_pagerduty/plugin.py, src/dispatch/plugins/dispatch_pagerduty/service.py, src/dispatch/plugins/dispatch_slack/feedback/interactive.py, src/dispatch/static/dispatch/src/service_feedback/api.js
Fixes a few errors in the oncall end-of-shift feedback reminder system: (1) the `reminder` wasn't being returned so the id wasn't stored correctly in the Slack message, (2) the hour sometimes is off in the scheduler which throws off the end-of-shift check, and (3) if no reminder in the db, deleting should be skipped. Also, this PR sets up an api call for fetching the feedback.
=> Fixes errors in oncall end-of-shift feedback reminders plus opens api to fetch feedback

src/dispatch/database/service.py, src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue, src/dispatch/static/dispatch/src/router/utils.js, src/dispatch/static/dispatch/src/search/utils.js
Allows the incident dashboard to also be filtered by a particular participant or commander. Fixes issue where members couldn't filter on participant. Changes URL to use email for filtering instead of name.
=> Allowing filtering in incident dashboard by participant or commander

src/dispatch/case/flows.py, src/dispatch/signal/flows.py
* Renamed the `create_resources` parameter to `create_all_resources`, as we do create some (e.g. conversation) even if it's set to `False`
* Removed ticket update call as we now always call `case_create_resources_flow`
=> Renames parameter create_resources to create_all_resources

src/dispatch/static/dispatch/src/entity/EntityFilterCombobox.vue, src/dispatch/static/dispatch/src/entity_type/EntityTypeFilterCombobox.vue, src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
The issue stemmed from us not returning entity types with the type `single`:
```vue
+ scope: ["multiple", "single"]
```
Which is the default type when created via the `+` -> Modal creation dialog (from within the definition edit sheet).
=> Fix bug where entity types created via Modal don't appear in combobox

src/dispatch/static/dispatch/src/search/SearchFilterCombobox.vue
When removing an engagement filter and having no filters set you have to use the combobox X next to the drop down selector and you can't simply remove a filter using the chip x otherwise the change isn't saved. 
you can directly emit changes from the remove method:
```vue
remove(item) {
const index = this.searchFilters.indexOf(item);
if (index !== -1) {
this.searchFilters.splice(index, 1);
this.$emit("input", this.searchFilters);
}
},
```
I believe this functionality is meant to be covered in the `set()` function:
```vue
set(value) {
this.search = null;
const filters = value.filter((v) => {
if (typeof v === "string") {
return false;
}
return true;
});
this.$emit("input", filters);
},
```
But the root cause of the issue seems to stem from:
```
To ensure the set() method within the …
```
=>  To allow deletable chips to be saved  for `SearchFilterCombobox.vue`, call `$emit` ('input') in remove method

src/dispatch/plugins/dispatch_slack/incident/interactive.py
It is possible that there are tasks, but there is no previous actions value so actions is None. This addresses that issue by setting actions to an empty string if it is None.
=> handle possible null actions in interactive.py

src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
Selecting a case via the checkbox in the table spawns a sheet at the bottom of the page, in Case table this steals focus, and you cannot close the bottom sheet. This does not happen on incident table, so we copy that one. Note, this component should likely be standardized in `@/components` in the future as they are basically the same.
=> Mirror the incident bottom sheet to prevent focus from being stolen

src/dispatch/static/dispatch/src/case/Table.vue, src/dispatch/static/dispatch/src/incident/Table.vue
The `id` was being returned instead of the entire `Case`/`Incident` object, this appears to be different behavior in the Vue3 Vutetify tables than how it used to work.
=> return object when an item is selected in case/incident table

src/dispatch/static/dispatch/src/auth/Login.vue, src/dispatch/static/dispatch/src/auth/Register.vue, src/dispatch/static/dispatch/src/case/DetailsTab.vue, src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/components/layouts/BasicLayout.vue, src/dispatch/static/dispatch/src/incident/ReportForm.vue, src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue, src/dispatch/static/dispatch/src/styles/index.scss
=> Aligns form styles and reverts project autocomplete

src/dispatch/static/dispatch/src/signal/engagement/SignalEngagementCombobox.vue
Selected Engagements would just be an empty chip in the combobox, this shows the name now.
=> Correctly render object title in SignalEngagementCombobox

src/dispatch/evergreen/scheduled.py, src/dispatch/plugins/dispatch_slack/enums.py, src/dispatch/plugins/dispatch_slack/plugin.py
This PR swallows exceptions being thrown if an evergreen message is attempted to be sent with no owner or a Slack message is attempted to be sent to an archived channel.
=> Swallow send exceptions

src/dispatch/plugins/dispatch_slack/fields.py
Current state is above, you do not know which value you are selection. This shows the `value` of the Entity, (e.g. `will@lol.com`)
=> Show the value of the Entity in Slack snooze dropdown

src/dispatch/static/dispatch/src/components/DateWindowInput.vue
Resolves:
```
Require self-closing on Vue.js custom components (<v-date-picker>)
```
=> Fix self closing custom component lint flag on DateWindowInput

src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue, src/dispatch/static/dispatch/src/case/Page.vue, src/dispatch/static/dispatch/src/components/RichEditor.vue
We check if the user is typing, and don't override the model value. We also debounce the save so it's less intensive.
=> debounce `tiptatp` editor save to not interfere with typing

src/dispatch/static/dispatch/src/case/GraphTab.vue
This label was too tightly coupled to the raw data, it should work across all Dispatch Signals now.
=> Display label correctly for SignalInstanceNode

src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
=> Show default participant icon and fix label for reporter

src/dispatch/plugins/dispatch_slack/case/messages.py
We ues the `id` instead of the name in the Case Page now since it saves a RT with current views.
=> Change `View` button for Case Slack message to use `id` as route parameter 

src/dispatch/case/messaging.py
We updated routes in the Case Page PR, fix old links.
=> Change `name` to `id` for reminder URL

src/dispatch/static/dispatch/src/case/priority/CasePrioritySearchPopover.vue, src/dispatch/static/dispatch/src/case/severity/CaseSeveritySearchPopover.vue, src/dispatch/static/dispatch/src/case/type/CaseTypeSearchPopover.vue, src/dispatch/static/dispatch/src/project/ProjectSearchPopover.vue, src/dispatch/static/dispatch/src/tests/SearchPopover.spec.js
```bash
✓ src/tests/SearchPopover.spec.js (9)
✓ mounts correctly
✓ toggles menu on button click
✓ updates selectedItem when selectItem is called
✓ updates searchQuery when text field input changes
✓ filters items based on searchQuery
✓ emits item-selected when an item is selected
✓ toggleMenu changes the value of menu
✓ updates selectedItem when initialValue prop changes
✓ updates items when items prop changes
Test Files  1 passed (1)
Tests  9 passed (9)
Start at  08:41:24
Duration  579ms
PASS  Waiting for file changes...
```
=> Get all items for Pri, Sev, Type, and Project in `SearchPopover` component and add tests

src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
=> Require all fields but tags, fix Submit button validation

src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue, src/dispatch/static/dispatch/src/tests/CaseStatusSelectGroup.spec.js
```bash
✓ src/tests/SearchPopover.spec.js (8)
✓ src/tests/LockButton.spec.js (2)
✓ src/tests/CaseStatusSelectGroup.spec.js (2)
Test Files  3 passed (3)
Tests  12 passed (12)
Start at  08:29:35
Duration  2.29s (transform 1.39s, setup 0ms, collect 4.97s, tests 302ms, environment 383ms, prepare 190ms)
PASS  Waiting for file changes...
press h to show help, press q to quit
```
=> Add CaseStatusSelect group tests, refactor to script setup, and fix a couple bugs

src/dispatch/static/dispatch/src/case/CaseSignalInstanceTab.vue
prevent button overlap on small viewports
=> use `flex-shrink` and `min-width 0` for signal instance tab viewer

src/dispatch/conversation/flows.py
@metroid-samus I think you had a similar PR recently to address this issue, just an FYI
=> Resolve unreferenced conversation variable in no target conditional case

src/dispatch/plugins/dispatch_slack/case/messages.py
I find that the `View` button is often overlooked. `Open in Dispatch` will make the button larger and is a clearer description of what the button does.
=> Change View Case button to Open in Dispatch

src/dispatch/feedback/service/views.py, src/dispatch/static/dispatch/src/feedback/service/store.js
Restricts viewing the oncall feedback table to admins and above.
=> Restricting oncall feedback permission

src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
=> Polish CaseStatusSelectGroup dialog when changing status

src/dispatch/static/dispatch/src/components/ParticipantSelect.vue
Fixes an error in the incident table filter dialog where a project wasn't first selected.
=> Only add project to participant filter if non-null

src/dispatch/feedback/service/scheduled.py
find_schedule_and_send uses did_oncall_just_go_off_shift which can return None if the previous on call 18 hours and 2 hours from run are the same. This will just return if that happens
=> Updated find_schedule_and_send to check for Null current on call

src/dispatch/plugins/dispatch_slack/plugin.py
It is possible that a message could be attempted to send for a slack account that does not exist anymore. This performs a check before attempting to send so it does not raise an exception if the user does not exist.
This causes two looks ups for every direct or ephemeral send, but will prevent exceptions.
=> Update slack plugin.py to check if user exists before send direct

src/dispatch/case/messaging.py
Updated return types for definitions, changed None checks to use "is None" instead of "not" and added a None check for assignee when sending case close reminders
=> Check for case assignee before trying to send reminder

docs/docs/user-guide/incidents/forms.mdx
Adding new doc page for forms.
=> Add doc page for forms

src/dispatch/event/service.py
The timeline events that were exported to doc was not sorted by timestamp. Added a fix to address it.
=> Fixed sorting during timeline export

src/dispatch/group/flows.py
incident.tactical_group can be None and if that is the case, this will handle it by ignoring and just log a warning.
=> Perform None check for group in update_group

src/dispatch/static/dispatch/src/case/DetailsTab.vue, src/dispatch/static/dispatch/src/case/TableExportDialog.vue, src/dispatch/static/dispatch/src/case/TableFilterDialog.vue, src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue, src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue, src/dispatch/static/dispatch/src/data/query/TableFilterDialog.vue, src/dispatch/static/dispatch/src/data/source/TableFilterDialog.vue, src/dispatch/static/dispatch/src/incident/TableExportDialog.vue, src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue, src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue, src/dispatch/static/dispatch/src/signal/NewEditDialog.vue, src/dispatch/static/dispatch/src/tag/TagPicker.vue
The new tag picker component was not watching the project prop for changes and thus was not filtering properly.
=> Ensuring that the tag picker reloads on project selection

src/dispatch/case/flows.py
I walked back from `Adding the following individuals to help resolve this case` to resolve an issue where Case reporter is not added to the Case conversation. We pass some variant of `participant_emails` all the way down from `case_create_resource_flow`, where this list of emails is populated. It looks like we never add reporter here, if it exists, even though we do it for the assignee.
=> Add reporter to individual_participants list

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Slack throws an error when a PlainTextInput has an empty string as the initial value. This field should be set to None when the initial value is empty.
=> Only populate the tacticall report actions field if there are current actions.

src/dispatch/static/dispatch/src/styles/tagpicker.scss, src/dispatch/static/dispatch/src/tag/TagPicker.vue
Adds ability to copy the list of tags as `tag_type/tag_name`. For instance, clicking the copy button at the end of the picker here
would copy the text `action/compromise, actor/researcher` to the clipboard.
=> Adding copy button to tag picker

src/dispatch/incident_cost/service.py
Calculate the participant role time by setting the participant's renounced at time to one of the following choices:
1. the current time if the incident is active
2. the time the incident is set to stable if the incident is stable
3. participant role renouncement time if the participant leaves their role before the incident is stable.
=> Fixes participant role time calculation by defaulting the participant role end time to now.

src/dispatch/auth/views.py
* This change removes the ability to change a user's password via API, as user password changes are only supported via CLI and not UI.
* We still allow for changes to default projects, and roles if the user requesting the role change has `Owner` role.
=> Do not allow user password changes via API

src/dispatch/conversation/service.py
Fixes an issue that may occur when a threaded conversation isn't looked up by a thread_id.
=> Fixing one_or_none error when conversation has multiple rows

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Reverts linter changes for `cost_model_select` creation. The `cost_model_block` was interpreted as a tuple rather than an object | None.
=> Revert linter changes

src/dispatch/static/dispatch/src/case/DetailsTab.vue, src/dispatch/static/dispatch/src/incident/DetailsTab.vue, src/dispatch/static/dispatch/src/signal/NewEditDialog.vue, src/dispatch/static/dispatch/src/tag/TagPicker.vue
This PR adds a new prop to the tag picker and hides the copy button by default. To show the copy button, set the `show-copy` prop.
=> Only show copy button in tag picker if prop is set

src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue, src/dispatch/static/dispatch/src/case/severity/CaseSeveritySelect.vue, src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue, src/dispatch/static/dispatch/src/incident/severity/IncidentSeveritySelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue, src/dispatch/static/dispatch/src/tag/TagPicker.vue
This PR adds validation to project-specific fields in incident and case selectors for types, priorities, severities, and tags.
=> Validate project-specific fields in UI

src/dispatch/plugins/dispatch_slack/enums.py
This endpoint enables Dispatch to fetch the contents of a Slack conversation thread.
This endpoint is referenced in `dispatch_slack/service.py`, but not added to the `dispatch_slack/enums.py` file.
=> Adds the Slack API endpoint for conversation replies.

src/dispatch/plugins/dispatch_google/drive/drive.py
The new deletion command is 'delete', not 'trash'.
How to test:
1. Create an incident with the Google Drive and/or Google Doc plugins enabled.
2. Delete the incident. Both the folder and docs will be deleted.
=> Updates the resource deletion call.

src/dispatch/plugins/dispatch_google/drive/drive.py
Google decided to change this at some point for v3, https://developers.google.com/drive/api/guides/v2-to-v3-reference. so now instead of calling trash, we have to set the property of trashed to True.
=> updated delete to trashed

src/dispatch/static/dispatch/src/incident/EditSheet.vue, src/dispatch/static/dispatch/src/incident/FormsTab.vue, src/dispatch/static/dispatch/src/router/config.js
Provides direct link to an incident's forms page.
Fixes a minor race condition bug.
How to test:
1. Navigate to `{DISPATCH_UI_URL}/default/incidents/{incident.name}/forms`
=> Adds routing to an incident's forms tab.

src/dispatch/plugins/dispatch_google/common.py, src/dispatch/plugins/dispatch_google/docs/plugin.py, src/dispatch/plugins/dispatch_test/document.py, tests/dispatch_google_docs/test_dispatch_google_docs.py
If the url of a hyperlink contains a placeholder, it will be replaced with the corresponding value in a replacements list.
For example, if we aim to substitute all instances of `{{name}}` in a Google Doc with `netflix`, a hyperlink that originally directed to `http://www.{{name}}.com` will be transformed into `http://www.netflix.com`
=> Replaces hyperlinks in a specified Google Doc.

src/dispatch/static/dispatch/src/tag_type/Table.vue
In https://github.com/Netflix/dispatch/pull/4430 / Add required as a tag type attribute, we added support for `Required` tag types, this PR adds a `Required` column that indicates whether a tag type is required in the backend tag type settings table.
After marking as required
Before marking as required
=> Add a Required column to the TagType table

src/dispatch/plugins/dispatch_slack/case/enums.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/enums.py, src/dispatch/plugins/dispatch_slack/plugin.py
This PR removes the `Raw Data` button from the Case thread and moves the alert JSON into a JSON file in a subsequent message in the thread. It does not appear to be possible to include the JSON file in the message where `Raw Data` was. I tested this locally by running through the signal instance creation flow via the `/signal_instances` API view.
This change makes the alert data more visible, adds syntax highlighting, and allows for larger alert JSON sizes (the Raw Data modal view was constrained to 2500 characters.
=> Add alert data to JSON file in Case thread, remove Raw Data button

src/dispatch/plugins/dispatch_slack/case/interactive.py
Fixes a bug where we attempt to send an after hours message when a message is sent to the main Case channel.
=> Do not process handle_case_after_hours_message outside of a thread context

.coveragerc, .github/workflows/python.yml, pytest.ini
Adds the following steps to the `Python Lint and Test / test (pull_request)` check:
- **Coverage per file**
-  Evaluates if each `*.py` file adheres to the suggested minimum code coverage level
- **Coverage total**
- Checks whether the overall Python code adheres to the suggested minimum code coverage level
Sample Run: https://github.com/Netflix/dispatch/actions/runs/8182093443/job/22372896340
=> Adds code coverage recommendations in GitHub workflow.

src/dispatch/plugins/dispatch_slack/case/interactive.py
Snooze filters created via Slack did not correctly set timezone to UTC, so they were always in the past. Additionally, the expression that was constructed did not match the expected format:
```json
[
{
"or": [
{
"model": "Entity",
"field": "id",
"op": "==",
"value": 35
}
]
}
]
```
We update how we build the `filter` we pass to `create_filter_expression`:
```python
if form_data.get(DefaultBlockIds.entity_select):
entities = [
{"id": int(entity.value)}
for entity in form_data[DefaultBlockIds.entity_select]
]
```
Which results in the correct expression.
This was tested E2E locally, debug output:
```bash
FOUND f=<SignalFilter #42> on INSTANCE with f.mode='active' and f.action='snooze' and f.expiration=datetime.datetime(2024, 3, 12, 19, 30, 36, 895947)
mode f.mode='active' was active
mode …
```
=> [Bugfix] - Timezone and expression construction for snooze created via Slack

src/dispatch/signal/flows.py, src/dispatch/signal/views.py
Race condition on entity extraction when a duplicate UUID goes through `create_signal_instance_flow` and `update_signal_instance_flow` simultaneously.
=> Do not extract new entities from updated instances

src/dispatch/incident/flows.py, src/dispatch/incident_cost/service.py, tests/factories.py, tests/incident_cost/test_incident_cost_service.py
This PR adds the following changes:
- Adds the incident review cost to the incident only when the incident review document is created.
- Updates the classic cost model to add new incident response costs since the last update instead of recalculating the entire cost.
- Refactors the Incident Cost service.
- Increases code coverage of the Incident Cost service to 90%.
- Improves documentation.
=> Updates classic cost model to append new response costs instead of overwriting them.

src/dispatch/incident_cost/scheduled.py, src/dispatch/incident_cost/service.py
How to test:
Run `dispatch scheduler start` and ensure that the incident costs are correctly updated.
=> Fixes calls to renamed incident cost functions

src/dispatch/plugins/dispatch_slack/plugin.py
Something is causing the an attempt to do something with an archived incident channel and incident. In this case, in the incident commander is removed from the channel because the slack account is deactivated and it is unclear why there is a job trying to add the person back. Trying to figure out where this is happening and the only thing, aside from updating all the calls with different notifications types, was to include the template. Then when/if it happens again, we can trace where it is coming from.
=> [Bug] Adding the message template in SlackAPIError when channel is archived

src/dispatch/plugins/dispatch_slack/plugin.py
Moved participant lookup to occur only if it is not archived because the participants will only be added if it is not archived. This created an issue when the participant look up failed because the slack account is deactivated, but the channel was archived so no need for any action anyway.
=> [Bug] moved participant lookup

src/dispatch/incident/flows.py
If an incident is closed, we expect the incident conversation to be closed as well. This will cause errors in slack, if we try to add someone to an archived conversation and send a message to that archived conversation.
=> [Bugs] Check incident status before re-adding IC

src/dispatch/static/dispatch/src/components/DateWindowInput.vue
Fixes time zone issue with converting date from URL (since default is UTC) by breaking down parts of date string.
=> Fixing date in date picker from modelValue

src/dispatch/signal/service.py
Added logic to test if signal_id is a guid and to only look at external_id if it is.
=> DISDEV-221 Fix get_by_primary_or_external_id by testing for uuid

src/dispatch/plugins/dispatch_slack/service.py
Update `does_user_exist` in slack/service.py to use the `get_user_info_by_email` and `make_call` functions. If the USER_NOT_FOUND error occurs from `make_call` it is expected to be raised again and handled in `does_user_exist`
=> Handle slack rate limit for does_user_exist

src/dispatch/incident/messaging.py
Log error instead of throwing exception when sending ephemeral message for task add.
=> Adding exception handling around message send

src/dispatch/incident/flows.py
Previously incidents created with the active status were not being populated with incident names and incident resources. This is due to a timeout with the `@timer` decorator in `incident_service.get()`.
This bug fix reintroduces the `@background_task` decorator to `incident_create_flow()`, enabling these resources to be created.
=> Fixes incident naming and incident resource creation during active incident creation.

src/dispatch/plugins/dispatch_pagerduty/service.py
The existing `get_oncall_email` method assumes that there is only one associated schedule with an on-call escalation policy.   In the event that more than one schedule exists (say, if there is a US and India team) and the second schedule is active, the method will attempt to find the on-call engineer in the first schedule & fail.
This fix updates the method to iterate over all `escalation_rules` in an attempt to find the on-call engineer.  Only after it has iterated over all schedules and not found an engineer will it throw an Exception.
```json
{
"description": "",
"escalation_rules": [
{
"escalation_delay_in_minutes": 30,
"id": "IDREDACTED",
"targets": [
{
"html_url": "https://company.pagerduty.com/schedules/IDREDACTED",
"id": "IDREDACTED",
"self": …
```
=> bug: pagerduty_plugin - Updates method for accessing current on-call email

src/dispatch/case/service.py, src/dispatch/case/views.py, src/dispatch/static/dispatch/src/components/NotificationSnackbarsWrapper.vue, tests/case/test_case_service.py, tests/factories.py
Return an error message to the user when reporting cases with no conversation targets. 
Case conversations are created as threads by default and require a conversation target to be created.
=> Cases should be created with a conversation target

src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue, src/dispatch/static/dispatch/src/incident/ReportSubmissionForm.vue
Ensuring that clicking on "Escalated" in the status group now brings up the escalation dialog. Also, fixing display error in incident type picker.
=> Clicking escalate in the status group brings up escalation dialog

src/dispatch/plugins/dispatch_slack/middleware.py
Immediately upon creating a channel, our company invites a compliance bot to the channel.  This bot advertises itself to the channel using the `is_bot` property in [apps.events.authorizations.list](https://api.slack.com/methods/apps.event.authorizations.list#examples).  Because this heuristic is not used in [is_bot](https://github.com/Netflix/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/middleware.py#L205), it is not recognized as a bot & throws an error when attempting to read the profile / email:
```python
ERROR:slack_bolt.App:'email'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/slack_bolt/app/app.py", line 536, in dispatch
middleware_resp, next_was_not_called = listener.run_middleware(req=req, resp=resp) …
```
=> bug: Updates is_bot to support bots defined in apps.event.authorizations.list

src/dispatch/incident/service.py
At present, when reporting a bug, the severity, no matter what is input in the dialog will default to the project's default severity.
Instead of depending on the default severity, this updates the incident service to use the incident severity service's `get_by_name_or_default` method just like the priority uses above.
=> bug: Accurately captures severity level at time of incident report

requirements-base.txt
=> Revert "Bump sentry-sdk from 1.45.0 to 2.1.1"

src/dispatch/incident/service.py
The IncidentUpdate's `incident_type` field is an IncidentTypeBase, which does not have an `id` field. Thus, the initial `id` comparison resulted in an error.
However, earlier in the `incident_service.update()` function call, the `incident_type` is already retrieved. We can perform the comparisons against this object's `id`.
=> Validate IncidentUpdate's incident_type field against the retrieved incident type.

src/dispatch/case/flows.py
For dedicated channel cases, we rename the channel to the name of the incident ticket on escalation. This currently happens twice, once where it was removed in this PR (at the end of the escalation flow) and at the beginning in `incident_create_resources`.
This is already done earlier here:
```python
def incident_create_resources(
*,
incident: Incident,
db_session: Session | None = None,
case: Case | None = None,  # if it was escalated, we'll pass in the escalated case
) -> Incident:
"""Creates all resources required for incidents."""
if not incident.ticket:
ticket_flows.create_incident_ticket(incident=incident, db_session=db_session)
if case and case.dedicated_channel and case.escalated_at is not None:
plugin = plugin_service.get_active_instance(
db_session=db_session, …
```
=> [Bugfix] - We rename case -> incident channel twice

src/dispatch/incident/flows.py
This fixes the parameter to `subject` in `add_conversation_bookmark`.
=> Changing to subject in add_conversation_bookmark

src/dispatch/plugins/dispatch_slack/incident/interactive.py
When attempting to define tags during incident reporting / updating in Slack, we were not seeing any tags autocomplete even though we have a large number associated w/ the selected project.
[handle_tag_search_action](https://github.com/Meandmybadself/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/incident/interactive.py#L233) uses `project_id` as defined in the BoltContext to query for tags associated with a project.  
This value is initially set in [subject_middleware](https://github.com/Meandmybadself/dispatch/blob/master/src/dispatch/plugins/dispatch_slack/middleware.py#L397) at the start of the interaction & never updated.
If the selected project is not the default project, this will return an empty set of tags.
When a project is defined/updated in the modal, we should …
=> bug: Fixes tags not showing up during incident report / update

src/dispatch/case/flows.py, src/dispatch/event/service.py, src/dispatch/participant/flows.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/plugins/dispatch_slack/middleware.py
Adds case participant functionality one would expect in incidents to dedicated channel cases. Such as, adding users as a participant on channel join, invalidaitng the participant, and sending them a welcome message. Fixes a bug in the escalate case command where form_data was not being passed and so priority/type options were not being respected.
=> [Enhancement] - Case participant slack functions, ephemeral message, and escalate bug fix

src/dispatch/plugins/dispatch_slack/case/interactive.py
Adds the initial assignee as the current assignee for Case update command, handle error if user doesn't exist so Modal still opens if that raise occurs.
=> Initial assignee not populated for case update command modal

src/dispatch/case/flows.py, src/dispatch/conversation/flows.py
This PR ensures that the channel topic for dedicated channel cases is updated when details about the case change.
=> Change topic in case channel on update

src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
AFAICT, the bolt SDK will only execute one of the registered functions for a given event subscription? case version was hitting for me locally. This immediately returns if you are not in a case context and thus the incident version is never invoked. This behavior seems kind of strange to me, you would think multiple functions could be registered to the same event, and I'd be curious to see if we can find any mention of this in the bolt documentation.
Either way, we can create a single function for both contexts. I kept it in incident for now since we don't have a spot for these shared functions at this very moment. We could add shared/subject folder or similar.
**Incident Participant Added**
**Case Participant Added**
=> bugfix: Bolt event subscriptions get hijacked by one of the funcs registered

src/dispatch/plugins/dispatch_slack/enums.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
When using the designated Slack reaction on a message with a user (or users) that have been tagged, the message previously came into the timeline with the user_id(s). This PR replaces those ids with the users' names.
Previously:
`<@WJK2RF4DD> do you have the files?`
Now:
`@David Whittaker do you have the files?`
=> Replace Slack user_ids in messages with names

src/dispatch/static/dispatch/src/components/PreciseDateTimePicker.vue
This PR adds the ability for the user to keep typing the date and time without having to Tab through each field, or use the Enter key to advance to the next field. This change also adds more robust key filtering.
=> Allow user to keep typing date time in PreciseDateTimePicker

src/dispatch/incident/messaging.py
The message always shows `Incident Role(s)` even if it's a case participant. This PR changes it to make it dependent on the subject type.
=> Fixes participant announcement message

src/dispatch/static/dispatch/src/forms/table/AttorneyEditForm.vue
This fixes a bug where the "Additional attorney questions" section would show even when there was no schema.
=> Don't show additional attorney questions section if schema is empty

src/dispatch/plugins/dispatch_slack/middleware.py
Adds additional check for is_bot flag in user info
=> Adds additional bot check.

src/dispatch/signal/service.py, tests/signal/test_signal_service.py
This PR fixes a bug where the user is unable to delete signal filters from the signal definition.
=> Enable removal of signal filters from signal definition.

src/dispatch/cli.py
Resolves:
```
AttributeError-'_GeneratorContextManager' object has no attribute 'query'
```
on
```python
install_plugins()
db_session = get_session()
organizations = get_all_organizations(db_session=db_session)
---> 
def get_all(*, db_session) -> List[Optional[Organization]]:
"""Gets all organizations."""
return db_session.query(Organization)   <---
```
=> bugfix: get_session() contextmgr usage in consume_signals()

src/dispatch/plugins/dispatch_slack/service.py
Removes sleep, defaults to exponential backoff. Respect slack API rate limiting.
=> Improve our slack api error handling and backoff

src/dispatch/plugins/dispatch_slack/service.py
I messed up when I recommended the return type. This format is correct.
=> Update slack_wait_strategy return type hint

src/dispatch/plugins/dispatch_slack/service.py
Don't retry adding users if they are already in the channel.
`make_call()` has a `retry` decorator which retries a failed api call. We do not want to retry handled errors.
=> Don't retry adding users if they are already in the channel.

src/dispatch/auth/permissions.py, src/dispatch/case/models.py, src/dispatch/case/views.py, src/dispatch/static/dispatch/src/case/CaseStatus.vue, src/dispatch/static/dispatch/src/case/Table.vue, src/dispatch/static/dispatch/src/case/api.js, src/dispatch/static/dispatch/src/case/store.js
You can join dedicated case channels, if it is not closed. You cannot join non-dedicated case channels and there is no concept of 'subscribe'
=> feat: add self-join button and api to cases

src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/plugins/dispatch_slack/service.py
Adds `already_in_channel` Slack error to skip retry and also a check for valid participant on `after_hours_message`
=> Adds Slack error code skip retry

src/dispatch/plugins/dispatch_slack/service.py
Does not retry for any item in the SlackAPIErrorCode enum
=> Skip retries for defined SlackAPIErrorCode

src/dispatch/case/flows.py, src/dispatch/case/messaging.py, src/dispatch/messaging/email/utils.py, src/dispatch/messaging/strings.py
This PR adds notifications to dedicated channel cases, announcing updates in the channel and allows for both updates and new cases to be sent to an announcement conversation and/or email via search filters.
=> Adding notifications to dedicated channel cases

src/dispatch/plugins/dispatch_slack/case/interactive.py
There is a bug where clicking the resolve button in a case thread does not update the other case resources. This PR fixes this.
=> Resolving a case thread should update the other case resources.

src/dispatch/incident/messaging.py, src/dispatch/messaging/strings.py, src/dispatch/plugins/dispatch_slack/service.py
This PR turns off unfurling links, to avoid this kind of bad preview. In addition, there is now a link to the conversation in the incident management tips message.
=> Turns off unfurling links and adds conversation link to help tips

src/dispatch/case/flows.py, src/dispatch/plugins/dispatch_slack/case/interactive.py
This PR fixes the following bug:
* When escalating a case via Slack, the user’s incident description is overwritten with the case description
How to test:
* In Slack, Report a case
* In the resulting case channel, type `/dispatch-escalate-case'
* Modify the description field and submit
* The new incident description should have the updated information as a prefix."
=> Do not overwrite description field

src/dispatch/messaging/email/filters.py, tests/conftest.py, tests/factories.py, tests/messaging/test_messaging.py
This PR prevents Jinja blocks from being executed. This occurs when messages are rendered.
=> security: Do not render blocks in Jinja message templates

src/dispatch/static/dispatch/src/incident/EditSheet.vue
This PR makes the tabs in the incident edit pane disabled until the incident data is returned and populated, preventing the tabs from appearing blank.
=> Disables tabs in incident edit until populated

src/dispatch/case/models.py, src/dispatch/incident/models.py
This PR fixes the empty commander, assignee, and reporter fields when paginating through cases and incidents using the API.
=> Removes subqueries to ensure pagination works

src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/config.py, src/dispatch/plugins/dispatch_slack/fields.py
Slack has a 3000 character limit on section text, so we're truncating the resolution text in case it is longer.
=> Truncate the case resolution reason text due to Slack limit

src/dispatch/cli.py
```
Please enter the database hostname (env = localhost): localhost
Please enter the database name (env = dispatch): dispatch
Are you sure you want to drop database: 'localhost:dispatch'? [y/N]: y
Success.
```
=> Asks user to type database hostname and name before asking for confirmation to drop database

src/dispatch/static/dispatch/src/case/TableFilterDialog.vue, src/dispatch/static/dispatch/src/case/priority/CasePriorityCombobox.vue, src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue, src/dispatch/static/dispatch/src/case/severity/CaseSeverityCombobox.vue, src/dispatch/static/dispatch/src/case/severity/CaseSeveritySelect.vue, src/dispatch/static/dispatch/src/case/type/CaseTypeCombobox.vue, src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue, src/dispatch/static/dispatch/src/incident/priority/IncidentPriorityCombobox.vue, src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue, src/dispatch/static/dispatch/src/incident/severity/IncidentSeverityCombobox.vue, src/dispatch/static/dispatch/src/incident/severity/IncidentSeveritySelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeCombobox.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeMultiSelect.vue, src/dispatch/static/dispatch/src/search/utils.js, src/dispatch/static/dispatch/src/service/NewEditSheet.vue, src/dispatch/static/dispatch/src/workflow/WorkflowSelect.vue
This PR fixes the sorting on selection controls and ensures filtering by project. We also ensure all calls to `createParametersFromTableOptions` are properly formatted with a model when passing a raw filter and corrected the sorting order paramater of `createSortExpression`.
=> Fixes selection ordering and includes project when filtering

src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Removing `shift_start_at` from metadata.
=> fix(scheduler): use correct metadata indexing

src/dispatch/static/dispatch/src/feedback/service/Table.vue
Fixes an error where empty details were throwing an error in the UI.
=> fix(ui): ensure empty details doesn't throw error

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-docs-test.yml, .github/workflows/deploy-docs.yml, .github/workflows/javascript.yml, .github/workflows/playwright.yml, .github/workflows/publish-image.yml, .github/workflows/python.yml, .github/workflows/stale.yml
**Description:**
Updated CI workflows with version bumps for GitHub Actions to the latest versions.
- `actions/checkout`: `v2/v3` → `v4`
- `actions/setup-node`: `v3` → `v4`
- `actions/setup-python`: `v2` → `v5`
- `actions/cache`: `v2/v3` → `v4`
- `peaceiris/actions-gh-pages`: `v3` → `v4`
- `actions/upload-artifact`: `v3` → `v4`
- `actions/stale`: `v3` → `v9`
=> update(ci): version bumps

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Contact plugin API calls make take time to run. This causes the Slack trigger to expire. This PR creates the modal immediately after the trigger and then populates the modal with the task fields after the API calls have completed.
=> Creates the modal immediately after invocation. Update the modal with the task fields after.

src/dispatch/cli.py
This pull request includes several changes to the `src/dispatch/cli.py` file, focusing on import optimizations, command adjustments, and the addition of a new performance testing utility.
* Reorganized imports to ensure proper order and avoid redundancy. (`src/dispatch/cli.py`) [[1]](diffhunk://#diff-b0d7a6fe8958049cdf1fbf6bdc0ef6aed6592c7ac1ffc8c69542f4c20a928902R8) [[2]](diffhunk://#diff-b0d7a6fe8958049cdf1fbf6bdc0ef6aed6592c7ac1ffc8c69542f4c20a928902L809-R813)
* Adjusted the import statements within the `dispatch_scheduler` function to ensure necessary modules are imported correctly. (`src/dispatch/cli.py`) [[1]](diffhunk://#diff-b0d7a6fe8958049cdf1fbf6bdc0ef6aed6592c7ac1ffc8c69542f4c20a928902R640) [[2]](diffhunk://#diff-b0d7a6fe8958049cdf1fbf6bdc0ef6aed6592c7ac1ffc8c69542f4c20a928902L6 …
=> Adds a command to perform signals testing to the CLI

src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/plugin.py
This pull request includes several updates to the `dispatch_slack` plugin to improve the handling of case messages, specifically around signal analysis and action buttons. The most important changes include updating function arguments to use `case` objects instead of `case_id`, enhancing the GenAI signal analysis message generation, and improving error handling and logging.
* Changed function arguments from `case_id` to `case` to streamline data handling and improve code readability in `create_signal_message`, `create_action_buttons_message`, and `create_genai_signal_analysis_message` functions. (`src/dispatch/plugins/dispatch_slack/case/messages.py`) [[1]](diffhunk://#diff-da2f1336a0f273a0b60f60e4c9bd48d5f7f0bf3af6ac817ce41cc79e5b1f66acL204-R205) …
=> Improves error handling, logging, and messaging in Slack plugin

src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/plugin.py
This pull request includes a change to the `create_threaded` method in the `dispatch_slack` plugin to handle the response from the `send_message` function and update the `signal_thread_ts` attribute of the `case` object accordingly. This change ensures the value of `signal_thread_ts` is the correct one when new alerts (aka signals) are ingested and the message needs to be updated with new counter.
Error handling and response management:
* [`src/dispatch/plugins/dispatch_slack/plugin.py`](diffhunk://#diff-84bac68ba28c626f61114b432a7c5b163f03541682e3efeb6d0dddc250a7caa8L127-R134): Modified the `create_threaded` method to capture the response from `send_message` and update `case.signal_thread_ts` if the response contains a timestamp.
=> Updates case.signal_thread_ts after creating the alerts section

src/dispatch/data/alert/service.py, src/dispatch/organization/service.py, src/dispatch/project/service.py, src/dispatch/service/service.py, src/dispatch/signal/service.py, src/dispatch/tag/service.py, src/dispatch/tag_type/service.py, src/dispatch/workflow/service.py
This pull request includes several changes across multiple files to improve type annotations and import organization. The most important changes involve updating function signatures to include type annotations and reorganizing imports for better readability.
* [`src/dispatch/data/alert/service.py`](diffhunk://#diff-65fc2ede653b957640f11342b83c3531e379bba33cb52e3d58e03d6c20c5276aL19-R20): Updated the `get_by_name_or_raise` function to include type annotations for the `alert_in` parameter.
* [`src/dispatch/organization/service.py`](diffhunk://#diff-8f2e2a892226548555aea19e5aef00ad1a93cc06ff6810ddf219587113851a99L47-R47): Updated multiple functions (`get_by_name_or_raise`, `get_by_slug_or_raise`, `get_by_name_or_default`) to include type annotations for the `organization_in` parameter. …
=> Fixes get_signal_engagement_by_name call in signals create module and several type annotations

src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/service.py, src/dispatch/signal/flows.py
This pull request includes several changes to the `dispatch_slack` plugin, focusing on improving the generative AI signal analysis message creation and code organization. The most important changes include adding a new configuration parameter for Slack conversations, refining the historical context generation, and improving code readability by reordering imports.
* [`src/dispatch/plugins/dispatch_slack/case/messages.py`](diffhunk://#diff-da2f1336a0f273a0b60f60e4c9bd48d5f7f0bf3af6ac817ce41cc79e5b1f66acR310-R315): Added `SlackConversationConfiguration` as a parameter to the `create_genai_signal_analysis_message` function and updated the function to use this configuration when including Slack messages from users. [[1]](diffhunk://#diff-da2f1336a0f273a0b60f60e4c9bd48d5f7f0bf3af6ac817ce41cc79e5 …
=> feat(GenAI): only include Slack user messages in historical context

.pre-commit-config.yaml, src/dispatch/signal/flows.py
This pull request includes several changes to improve logging messages and streamline test execution. The most important changes involve updating log messages in the `engage_signal_identity` function and modifying the test entry in the pre-commit configuration.
* [`src/dispatch/signal/flows.py`](diffhunk://#diff-7c970d67d7312044b55dff3c0e55201b519ced4431a0ee3a4d6d9b4a3b35e40eL196-R196): Updated log messages in the `engage_signal_identity` function to include the signal name along with its ID for better clarity. [[1]](diffhunk://#diff-7c970d67d7312044b55dff3c0e55201b519ced4431a0ee3a4d6d9b4a3b35e40eL196-R196) [[2]](diffhunk://#diff-7c970d67d7312044b55dff3c0e55201b519ced4431a0ee3a4d6d9b4a3b35e40eL208-R208)
* [`.pre-commit-config.yaml`](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf0 …
=> Improves warning text when there are no users to engage

src/dispatch/incident/scheduled.py, src/dispatch/messaging/strings.py
This PR fixes the weekly incident report to run weekly instead of daily. Also ensured that an empty report wasn't sent in the case of all restricted incidents for that week, instead a notice is sent that indicates there were no incidents to report on.
=> fix(scheduler): weekly reports should run weekly

docker/docker-compose.yml
This pull request includes minor changes to the `docker/docker-compose.yml` file. The changes add comments to the default passwords for PostgreSQL and pgAdmin, indicating that they should be changed.
* [`docker/docker-compose.yml`](diffhunk://#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03L10-R10): Added comments to the `POSTGRES_PASSWORD` and `PGADMIN_DEFAULT_PASSWORD` fields to indicate that the default passwords should be changed. [[1]](diffhunk://#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03L10-R10) [[2]](diffhunk://#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03L24-R24)
=> Adds comments to docker-compose.yml file to change default passwords

src/dispatch/static/dispatch/src/tag/TagPicker.vue
Fixes vue warning as the component has multiple root nodes.
```
[Vue warn]: Extraneous non-props attributes (label) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
```
=> Fixes warning

utils/github_utils.py
This PR adds the "docker" type to the possible list of PR labels in the github utils.
=> fix(utils): adding docker type to github utils

src/dispatch/plugin/models.py
Allows a list of strings as an option for the plugin metadata value.
=> fix(plugin): allow list of strings in plugin metadata

src/dispatch/plugin/models.py
Allows a dictionary as an option for the plugin metadata value.
=> fix(plugin): allow dictionary in plugin metadata

tests/incident_cost/test_incident_cost_service.py
Occasionally `test_calculate_incident_response_cost_with_cost_model` will fail due to rounding. This PR fixes the rounding errors.
=> fix(test): adding rounding method to quantize

tests/incident_cost/test_incident_cost_service.py
This PR amends [PR 5368](https://github.com/Netflix/dispatch/pull/5368) to use the correct rounding strategy.
=> fix(test): use correct rounding strategy

docker/Dockerfile
The move to python 3.14 breaks the docker build. The srsly package doesn't have a compatible wheel with anything above 3.12 right now ([docs](https://github.com/explosion/srsly/releases/tag/v2.4.8)), and it's using deprecated methods, so it can't be built by 3.14 yet. Because of this, `docker build .` is broken on master.
=> bug(docker): Revert python version bump

src/dispatch/signal/views.py
typo in the signal filter update flow: `get_signal_filter() got an unexpected keyword argument 'signal_id'`
=> (fix) get_signal_filter arg name is signal_filter_id

src/dispatch/plugins/dispatch_google/groups/plugin.py
This PR fixes the retry loop caused when a member isn't part of a Google Group and we try to remove them. Fixes DISDEV-80.
=> fix(groups): propagate errors back to remove_member

src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue, src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue, src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
We need to check that the last project exists to account for situations where we are loading in existing data.
=> Fixing selects when not yet loaded

.pre-commit-config.yaml, src/dispatch/case/flows.py, src/dispatch/plugins/dispatch_slack/case/interactive.py
- Updated the version of the `ruff-pre-commit` hook from `v0.6.4` to `v0.7.0`.
- Updated the version of the `typos` hook from `v1.24.5` to `v1.26.1`.
- Reordered imports in `src/dispatch/case/flows.py` for better readability and organization.
- In `case_update_flow`, added checks to ensure that the reporter or assignee email has changed before running the `case_assign_role_flow` and updating the tactical group. This prevents unnecessary operations if the emails haven't changed.
- In `handle_resolve_submission_event` within `src/dispatch/plugins/dispatch_slack/case/interactive.py`:
- Renamed `case` to `current_case` for clarity.
- Simplified the logic by directly using `current_case` for updates and notifications.
- Ensured that the case update flow and message updates use the updated case …
=> Speeds up case resolution

src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue, tests/static/e2e/report-submission.spec.ts
This PR fixes the incident type dropdown look ahead since the validator looks at the item list for validation.
=> fix(ui): increasing type selector length

src/dispatch/case/flows.py
This PR fixes an oversight in reading the email for case reporter and assignee.
=> fix(case): ensure participant read through individual

src/dispatch/feedback/incident/messaging.py, src/dispatch/feedback/incident/scheduled.py, src/dispatch/feedback/incident/service.py, src/dispatch/messaging/email/utils.py, src/dispatch/messaging/strings.py
This PR adds daily emails of any case feedback to the case assignees.
=> feat(case): add case feedback daily email

src/dispatch/case/flows.py, src/dispatch/plugins/dispatch_slack/case/interactive.py
This PR adds ticket updates to the Slack case status change flows. Fixes DISDEV-15.
=> fix(case): ensure case tickets are updated

src/dispatch/static/dispatch/src/case/DetailsTab.vue, src/dispatch/static/dispatch/src/incident/DetailsTab.vue
This PR fixes the New button to allow project selection when creating a new case or incident, but keeps the project selector disabled when editing an existing case or incident.
=> fix(ui): only disable project if editing existing case or incident

src/dispatch/definition/views.py, src/dispatch/document/views.py
This PR fixes the docstring for the `get_definition` and `get_document` routes.
=> Fix docstring for get_definition and get_document routes

src/dispatch/plugins/dispatch_google/groups/plugin.py
This PR logs when a groupkey no longer exists.
=> fix(groups/plugin): log when group no longer exists

src/dispatch/plugins/dispatch_slack/case/interactive.py
This PR fixes the manual engagement by replacing the form_data lookup with the participant id.
=> fix(slack): using participant id for manual engagement 

src/dispatch/plugins/dispatch_core/plugin.py
This PR checks to see if the MFA challenge was already approved before throwing an exception.
=> fix(plugin): check if challenge is already approved before raising exception

src/dispatch/static/dispatch/src/incident/EditEventDialog.vue
This PR fixes the possible slowdown caused by editing an event on the timeline with a lot of events by using a local copy of the event attributes in the edit dialog instead of editing `currentEvent` directly.
=> fix(ui): use local event to prevent slow down

src/dispatch/database/revisions/tenant/versions/2024-11-04_928b725d64f6.py
If upgrading twice, we could run into an error if the database index and columns were already dropped.
=> fix(db): fixes migration to ensure index and column exist before dropping

src/dispatch/database/service.py
This pull request addresses a potential issue in the `search_filter_sort_paginate` function within the database service by ensuring that the `filter_spec` is of type `str` before attempting to deserialize it using `json.loads`.
- **Type Check for Deserialization**:
- Added a type check to ensure `filter_spec` is a string before calling `json.loads`.
- This prevents errors that could occur if `filter_spec` is not a string, enhancing the robustness of the deserialization process.
- **`src/dispatch/database/service.py`**: 
- Modified the `search_filter_sort_paginate` function to include a type check for `filter_spec`.
- Modified the type signature for `filter_spec` to reflect that it can be `None`, `str`, or a `dict`.
- Added a comment to help future developers understand why the type check …
=> fix(db): ensure type is str before trying to deserialize

src/dispatch/case/flows.py
=> fix(logging): log case has been linked to incident when incident has a name

src/dispatch/signal/service.py, src/dispatch/signal/views.py, src/dispatch/static/dispatch/src/signal/DeleteDialog.vue, src/dispatch/static/dispatch/src/signal/Table.vue, tests/signal/test_signal_service.py
=> Revert "Removes option to delete a signal definition"

src/dispatch/static/dispatch/package-lock.json, src/dispatch/static/dispatch/package.json, src/dispatch/static/dispatch/src/incident/EditSheet.vue, src/dispatch/static/dispatch/src/main.js
Fixes the deprecated resize drawer to point to updated library. This allows the incident pane to be correctly resized.
=> fix(ui): fixes broken resize component

src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/case/messages.py
This pull request introduces several key updates to the manual MFA engagement process and enhances user management within Slack channels. The changes aim to streamline the user engagement workflow and improve the clarity of engagement messages.
1. **Removal of Signal Text from Manual MFA Engagement:**
- The signal text has been removed from the manual MFA engagement process to simplify the message structure and focus on essential information.
2. **Addition of User to Slack Channel:**
- Implemented functionality to add users to the relevant Slack channel during the engagement process, ensuring they are part of the conversation and can receive necessary updates.
3. **Code Refactoring:**
- Refactored the `handle_engage_user_command` and `engage` functions to improve readability and …
=> feat(slack): remove signal text from manual mfa engage and add user to channel

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Ensures only one slash in tag input before trying to unpack. Fixes DISDEV-315.
https://github.com/user-attachments/assets/19511ddb-e24f-43e1-b791-2353b9da5b1a
https://github.com/user-attachments/assets/b8f63370-7df5-49cb-a140-6fdde626aff4
=> fix(slack): ensure only one slash in tags

src/dispatch/plugins/dispatch_slack/case/enums.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/fields.py, src/dispatch/plugins/dispatch_slack/middleware.py, src/dispatch/plugins/dispatch_slack/models.py
This feature enhancement introduces the ability to add users to a threaded case in Slack when they are mentioned. This functionality aims to streamline collaboration by ensuring that all relevant participants are included in the case discussions.
1. **New Enum Values**: 
- Added `add_user` and `do_nothing` actions to `CaseNotificationActions` in `enums.py`.
2. **User Mention Handling**:
- Implemented `handle_user_mention` function in `case/interactive.py` to detect user mentions in messages.
- Extracts mentioned users and checks if they are part of the case.
- Sends a private message to the user who mentioned others, offering to add the mentioned users to the case.
3. **User Addition Workflow**:
- Added `add_users_to_case` function to handle the addition of users to a case when the "Add …
=> feat(slack): add users to threaded case on mention

src/dispatch/plugins/dispatch_slack/case/interactive.py
Changes MFA prompt link to a button click due to some issues with text-based link on mobile.
=> feat(mfa): change mfa prompt link to button

src/dispatch/task/service.py
This bug surfaced when a user was assigned a task that wasn't already in the incident. Fixes DISDEV-392.
=> fix(task): be sure to add user to incident before sending ephemeral message

src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue, src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue, src/dispatch/static/dispatch/src/service/ServiceSelect.vue
This pull request addresses an issue with the edit pane in the case type UI. The changes ensure that the project and incident project are correctly fetched and assigned, and updates the way project IDs are handled across different components. 
The main changes include:
1. **`NewEditSheet.vue`:**
- Enhanced the logic for setting `project` and `incidentProject` within the `created` lifecycle hook. The code now correctly fetches and assigns the project data fetched from the API.
2. **`IncidentTypeSelect.vue`:**
- Simplified the filter options by removing redundant `project_id` assignment, ensuring that the correct project is always applied.
3. **`ServiceSelect.vue`:**
- Corrected the assignment of `project_id` in filter options, changing it from a map operation to direct access, which is …
=> fix(ui): fixes edit pane on case type

src/dispatch/plugins/dispatch_google/groups/plugin.py
=> fix(groups): limit group_key username to first 60 characters

src/dispatch/static/dispatch/src/incident/TimelineReportTab.vue
Show a message in the UI if there are no tactical reports instead of an empty timeline.
=> feat(ui): show message if no tactical reports

src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Fixes a bug that doesn't properly filter the incident type for the selected project.
=> fix(ui): filter incident type by selected project

src/dispatch/database/revisions/tenant/versions/2024-11-04_928b725d64f6.py
Looks like a migration was realigning after some incident, but we do not have a foreign key constraint it's removing.
This PR makes the statement conditional.
When upgrading from [v20241011](https://github.com/Netflix/dispatch/releases/tag/v20241011) to latest:
```
[..]
INFO:Running upgrade 3edb0476365a -> 928b725d64f6, Fixes automatic generation issues:/usr/local/lib/python3.11/site-packages/alembic/runtime/migration.py:run_migrations:618
Traceback (most recent call last):
[..]
File "/usr/local/lib/python3.11/site-packages/dispatch/database/revisions/tenant/versions/2024-11-04_928b725d64f6.py", line 55, in upgrade
op.drop_constraint("project_stable_priority_id_fkey", "project", type_="foreignkey")
[..]
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) constraint …
```
=> fix(db): make migration statement conditional

src/dispatch/static/dispatch/src/case/store.js
This PR fixes a a bug where case polling continues even after all its resources have been created
=> End polling for case details after conversation has been created.

src/dispatch/workflow/models.py, src/dispatch/workflow/views.py
This will prevent unintended `plugin_instance` information disclosure.
=> Adds additional permissions and switches to minimal

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-docs-test.yml, .github/workflows/deploy-docs.yml, .github/workflows/python.yml, README.md, docker/Dockerfile, docs/docs/administration/installation.mdx, docs/docs/administration/settings/messaging.mdx, docs/docs/support.mdx, docs/docusaurus.config.js
Updating references to new main branch name
=> fix: updating main branch name

src/dispatch/case/views.py, src/dispatch/database/service.py, tests/database/test_service.py
This PR fixes the search filter's "filter by Incident Commander/Assignee" by undoing a portion of changes made in https://github.com/Netflix/dispatch/pull/5564.
=> Revert changes made to database service's include logic.

src/dispatch/static/dispatch/src/feedback/service/TableFilterDialog.vue, src/dispatch/static/dispatch/src/service/ServiceSelect.vue
This PR makes the oncall selector single-select by default. Only the oncall feedback filter dialog needs multiple-select, so adding a prop for that use case.
=> fix(ui): oncall select should default to single select

src/dispatch/auth/permissions.py, src/dispatch/organization/views.py
We throw an error if the new organization's slug coincides with an existing one.
=> fix(organization): disallow creation of org with existing slug

src/dispatch/auth/service.py
In #5711, the UserUpdate class no longer has the [password attribute](https://github.com/Netflix/dispatch/pull/5711/files#diff-15d6b1465c4dfa6598f562b0f3fa0f30d72ad4af62906e1b2363e62c4bc1e467L168) but the update function still checked for it and `dispatch user update -o` would throw an error.
Validated that user create (UI) and password reset (CLI) still functions.
=> fix: user update from CLI threw AttributeError

src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
This pattern matches the way Incident ReportSubmissionCard is set up since there isn't a "Load More" and fixes the issue where this.project isn't set in time for the evaluation
=> fix: case type query params get ignored on Report Case form

requirements-base.in, requirements-base.txt, requirements-dev.in, requirements-dev.txt
Tests are running and pytest exiting correctly.
```
tests/term/test_term_service.py::test_get PASSED                                                                                                       [ 95%]
tests/term/test_term_service.py::test_create PASSED                                                                                                    [ 95%]
tests/term/test_term_service.py::test_update PASSED                                                                                                    [ 96%]
tests/term/test_term_service.py::test_delete PASSED                                                                                                    [ 96%]
tests/ticket/test_ticket_service.py::test_get PASSED …
```
=> Downgrades and pins pytest version

src/dispatch/ai/service.py, src/dispatch/incident/flows.py, src/dispatch/incident/scheduled.py, src/dispatch/incident/service.py, src/dispatch/incident/views.py
- Added imports for `Visibility` and `Incident`.
- Simplified the `generate_case_signal_summary` function by modifying how the response is processed.
- Introduced a new function `generate_incident_summary` to create summaries for incidents, with checks for visibility, review documents, and plugin availability.
- Replaced the call to `incident_service.generate_incident_summary` with `ai_service.generate_incident_summary` in the `incident_closed_status_flow` function.
- Reorganized imports and added import for `ai_service`.
- Replaced the call to `incident_service.generate_incident_summary` with `ai_service.generate_incident_summary` in the `incident_report_weekly` function.
- Removed the `generate_incident_summary` function, which has been moved to `ai_service`.
- Reorganized imports and …
=> Moves generate_incident_summary() to AI service module and refactors code

requirements-base.in, requirements-base.txt, src/dispatch/ai/service.py
- Added `tiktoken` package to requirements
- Updated several package versions:
- `aiohappyeyeballs` from 2.4.4 to 2.4.6
- `aiohttp` from 3.11.11 to 3.11.12
- `boto3` from 1.36.13 to 1.36.19
- `botocore` from 1.36.13 to 1.36.19
- `google-api-python-client` from 2.160.0 to 2.161.0
- `numpy` from 2.2.2 to 2.2.3
- `openai` from 1.61.0 to 1.62.0
1. **New Constants**
- Added `MAX_TOKENS = 128000` constant
2. **New Functions**
- Added `num_tokens_from_string(message: str, model: str) -> tuple[list[int], int, tiktoken.Encoding]`
- Calculates token count for a given string using specified model
- Returns tokenized message, token count, and encoding object
- Added `truncate_prompt(tokenized_prompt: list[int], num_tokens: int, encoding: tiktoken.Encoding) -> str`
- Truncates prompts that exceed the …
=> Truncate GenAI prompt if this exceeds 128k tokens

src/dispatch/auth/views.py
Hi,
There is an IDOR vulnerability that allows any user to edit another user (via the Experimental Features button), by simply changing the user ID in the path and in the HTTP request. This happens because the application is missing a security check (when "role" is not provided in the PUT HTTP Request's body)
This additional security check will cause the application to return a 403 Forbidden if a user that is not an "Owner" is trying to edit another user, essentially remediating an IDOR vulnerability.
=> Propose additional security check to auth/views.py

src/dispatch/conversation/flows.py
This pull request addresses an issue in the `add_conversation_bookmark` function where bookmarks could not be added if the `resource` object lacked a `name` attribute. The changes ensure that a bookmark can still be created by using alternative identifiers when `resource.name` is unavailable.
- **Refactored Resource Name Handling**: 
- Introduced a new logic to determine `resource_name` when `resource.name` is not present. It now checks for `resource.resource_type` and uses `deslug_and_capitalize_resource_type` to generate a name. If neither is available, it defaults to the provided `title` or "untitled resource".
- **Updated Log Messages**:
- Modified log messages to use `resource_name` instead of directly accessing `resource.name`, ensuring consistent and meaningful logging even when …
=> fix(conversation): fixing bookmarks without resource.name

src/dispatch/static/dispatch/src/task/Table.vue
The API doesn't return data for incident_type for the Tasks API, and priority was named differently.
=> fix: Remove Incident Type from Tasks

src/dispatch/plugins/dispatch_slack/plugin.py
- Updated the Slack file upload method from `files_upload` to `files_upload_v2` in the `SlackConversationPlugin` class
- Changed parameter name from `channels` to `channel` to match the new API requirements
- Modified the channel value to use the conversation ID from `signal_response.get("id")` instead of using `conversation_id`
- Added a comment explaining that we need the conversation ID, not the name
- Removed the `filetype="json"` parameter as it's no longer needed in the v2 API
This change ensures compatibility with Slack's updated file upload API.
=> Migrates to Slack file upload v2 API call

setup.py, src/dispatch/config.py, src/dispatch/plugins/bases/investigation_tooling.py, src/dispatch/plugins/dispatch_slack/case/enums.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/case/messages.py
=> (feat): Adds support for opening investigations in an external tool from Slack case notifications

src/dispatch/static/dispatch/src/case/BulkEditSheet.vue, src/dispatch/static/dispatch/src/incident/BulkEditSheet.vue
Previously, after selecting an incident or case, the content was no longer scrollable due to the bottom sheet appearing. This fixes that scroll lock. Fixes DNRPLAT-94
=> fix(ui): make content scrollable when bottom sheet is visible

src/dispatch/plugins/dispatch_slack/case/messages.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
Fixes an issue when the description is too large and exceeds the maximum length for a section text block in Slack (3000 characters). Fixes DNRPLAT-96.
=> fix(slack): truncate description if too large

src/dispatch/cli.py, src/dispatch/plugins/dispatch_slack/case/messages.py
=> feat(slack plugin): moves investigate button to actions section

src/dispatch/case/enums.py, src/dispatch/case_cost/scheduled.py, src/dispatch/case_cost/service.py, src/dispatch/case_cost_type/models.py, src/dispatch/case_cost_type/service.py, src/dispatch/database/revisions/tenant/versions/2025-03-04_da444de005a6.py, src/dispatch/static/dispatch/src/case_cost_type/NewEditSheet.vue, src/dispatch/static/dispatch/src/case_cost_type/Table.vue, src/dispatch/static/dispatch/src/case_cost_type/store.js, tests/case_cost/test_case_cost_service.py, tests/case_type/test_case_type_service.py, tests/factories.py
Prerequisite for implementing parallel cost model execution for cases, allowing both the new cost model and classic cost model to run simultaneously and maintain separate cost records.
In this PR, we:
*  replace the `cost_type` `default` column with a `cost_model_type` column:
*  model_type=new is the response cost type associated with the new cost model
*  model_type=classic is the response cost type associated with the classic cost model
*  model_type=None is a cost type that is not associated with response time. This would cover manually-added costs accumulated over the course of the incident.
*  Update scheduler code to create a case response cost type and case response costs if none exist.
*  Update the UI to indicate which cost types are tied to response costs.
=> Migrate from using default case cost type to assigning cost type by cost model.

src/dispatch/plugins/dispatch_slack/case/messages.py
This PR fixes a bug where the GenAI analysis message exceeds 3000 characters. Block Kit can only render text sections with a maximum of 3000 characters.
=> Truncate the GenAI analysis message if it exceeds Block Kit's maximum length of 3000 characters

src/dispatch/plugins/dispatch_slack/case/messages.py
Returns the case name in the case threads that was erroneously removed in https://github.com/Netflix/dispatch/pull/5267.
=> bugfix(Slack/case): returning case name to thread message

src/dispatch/plugins/dispatch_slack/enums.py, src/dispatch/plugins/dispatch_slack/plugin.py, src/dispatch/plugins/dispatch_slack/service.py
This PR provides a way for the Slack plugin to remove users from a Dispatch-managed channel. Partially addresses DNRPLAT-122.
=> feat(slack): adds ability to remove users from channel

src/dispatch/static/dispatch/src/case/CostsTab.vue
Improves case cost UI to make toggling between Classic Cost Model costs and New Cost Model costs more intuitive.
=> Improve case cost UI

src/dispatch/ai/service.py
- Added `get_model_token_limit()` function that returns maximum token capacity for different LLM models
- Included support for latest models (GPT-4o, Claude 3.5/3.7 Sonnet)
- Implemented a safety buffer parameter (default: 5%) to prevent hitting absolute limits
- Updated `truncate_prompt()` to use model-specific limits instead of fixed values
- Enhanced function signature to accept the model token limit as a parameter
- Improved logging to show the actual token limit being applied
- Modified prompt processing in signal and incident summary generation
- Each function now dynamically calculates appropriate token limits based on the model in use
- Applied consistent approach across different generation functions
- **Model-Specific Handling**: Each model gets appropriate token limits based on …
=> fix(ai): improves handling of llm context window limit

src/dispatch/static/dispatch/src/case/CostsTab.vue
In the cases landing page, the case costs reflect the classic cost model by default. This should be reflected in the case costs tab as well.
=> (bugfix/case) Toggle the classic case costs on by default.

src/dispatch/signal/service.py
Fixes an issue where the signal contains a service, priority, or type that doesn't exist in the system.
=> fix(signal): guard against object not found when recording changes

src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
This PR fixes an off-by-one pagination error in the case type selector's "load more" button.
=> fix(case): report case types not loading more

src/dispatch/plugins/dispatch_jira/plugin.py
This PR fixes an error that occurred when a fallback default ticket was created for a case but used a resource_id pointing to a non-existing incident.
=> fix(jira): fallback to case ticket resource name

src/dispatch/case/flows.py, src/dispatch/case/messaging.py
This pull request enhances the event paging message functionality by dynamically including the on-call team's name in the notification. The changes ensure better clarity for users by specifying the relevant team to contact for immediate assistance.
Example:
=> Add oncall display name when sending option to page the oncall

src/dispatch/case/messaging.py
This PR provides extra clarity in the Slack message method to engage the oncall for a Case Type.
=> fix(slack): Case engage oncall language

src/dispatch/plugins/dispatch_slack/case/interactive.py
Adds a button to the Snooze Signal modal that goes directly to the signal viewer in the Dispatch UI, allowing the user to add a new entity type quickly.
=> feat(slack): adds add entity button in snooze modal

src/dispatch/case/models.py, src/dispatch/case/views.py, src/dispatch/incident/views.py
A user reported that `include[]=participants` hasn't been working for a few months. We currently are using the [`CasePagination`](https://github.com/Netflix/dispatch/blob/main/src/dispatch/case/models.py#L386-L391) for [`get_cases`](https://github.com/Netflix/dispatch/blob/main/src/dispatch/case/views.py#L135) but I think we should use `CaseExpandedPagination` to support all `include[]` options.
=> fix: allow GET on incidents/cases to include participants & other fields

src/dispatch/database/service.py, src/dispatch/static/dispatch/src/case/TableFilterDialog.vue, src/dispatch/static/dispatch/src/case_cost/CaseCostCard.vue
Allows for filtering out selected cases type(s).
=> feat(ui): adds ability to filter out selected case types

src/dispatch/static/dispatch/src/incident/TimelineTab.vue, src/dispatch/static/dispatch/src/styles/timeline.css
This PR ensures that timeline events wrap even if the text does not have any whitespace.
=> fix(ui): force wrap on timeline events

src/dispatch/plugins/dispatch_slack/case/interactive.py
The option to add entities doesn't currently show up unless some entities currently exist. This pulls out the conditional to display the option to add entities regardless of whether entities already exist in the signal.
=> (slack) show case add entities button even if no entities currently

.vscode/settings.json, src/dispatch/auth/models.py, src/dispatch/cli.py, src/dispatch/signal/service.py, src/dispatch/signal/views.py, src/dispatch/static/dispatch/src/signal/api.js
This PR creates two endpoints to update the signal defintion, one that allows the signal filters (snooze, deduplication) to be overwritten (a new endpoint just for the UI), and one that only allows addition of new signal filters (the existing endpoint). It also fixes a discrepancy with the cli check that wouldn't allow a database init and restore if the db didn't previously exist.
=> fix(signal): keep existing filters on signal update

src/dispatch/conference/models.py, src/dispatch/document/models.py
This PR updates the code to support Pydantic v2 by switching to the new ValidationInfo object for field validators. Key changes include updated import statements and modifications to the validator method signatures in both document and conference models.
=> fix(models): updating to Pydantic v2 ValidationData

src/dispatch/plugins/dispatch_slack/models.py
This PR updates the Slack payload model to accept numeric subject IDs by enabling Pydantic’s coercion of numbers to strings.
=> fix(slack): allow subject.id to be a number

src/dispatch/project/models.py, src/dispatch/signal/models.py
This PR adds default None values to several optional fields in signal and project models to allow missing parameters without validation errors.
=> fix(signal): set to None to allow missing parameters

src/dispatch/auth/models.py, src/dispatch/data/alert/models.py, src/dispatch/email_templates/models.py, src/dispatch/entity/models.py, src/dispatch/entity_type/models.py, src/dispatch/notification/models.py, src/dispatch/plugin/models.py
This PR updates various model classes to add default None values to optional attributes, ensuring that object creation behaves consistent with previous Pydantic version.
=> fix(models): adding default None to create objects with optional attributes

src/dispatch/plugins/dispatch_slack/fields.py
This PR fixes an issue where PlainOption in Slack blocks requires string values by explicitly converting the "value" keys in options and initial_option dictionaries to strings.
=> fix(slack): PlainOption requires string values

src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py
This PR converts various IDs from strings back to integers for Slack-related incident and case interactions.
Convert project, incident, case, and other ID values using int() to ensure proper type handling.
Applies similar changes across both incident and case interactive modules.
=> fix(slack): convert ids back from string to int

src/dispatch/individual/models.py, src/dispatch/plugin/models.py, src/dispatch/static/dispatch/src/plugin/store.js
This PR fixes an issue where plugin configuration fails to load by migrating from the deprecated Pydantic 1 encoder to the new JSON encoding approach in Pydantic 2. The key changes include:
- Updating the configuration serialization in plugin models using json.dumps with model_dump.
- Adding logic in the Formkit conversion to handle json_schema anyOf conditions.
- Adjusting type annotations in plugin and individual models for better compatibility with Pydantic 2.
=> fix(plugin): fixes plugin configuration not loading

src/dispatch/plugins/dispatch_slack/incident/interactive.py
This PR addresses an issue in the Slack notifications plugin by fixing the initial value for notification group updates.
- Updated the PlainTextInput component to conditionally set its initial_value based on available member data.
- Modified the submission event handler to correctly derive current_members when no initial_value is provided.
=> fix(slack): fixing initial value for notification group update

src/dispatch/auth/models.py
This PR fixes an issue with the auth models by setting a missing default value for the `experimental_features` field in the `UserRead` model.
=> fix(auth): adding missing default

src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
This PR addresses a lint error related to duplicate variable naming in the participant search popover component. It updates the iteration variable in the v-for loop and adjusts associated references accordingly.
=> fix(ui): fixes participant lint error

src/dispatch/plugins/dispatch_slack/plugin.py
This PR updates the `fetch_activity` call in the Slack plugin to use named arguments instead of positional ones for improved readability and to solve ordering problems.
=> fix(slack): change positional to named arguments

src/dispatch/ai/service.py
This PR updates the case query mechanism in the AI service to replace the deprecated from_self() function with an explicit subquery and alias approach. The changes ensure compatibility with SQLAlchemy 2.0 while maintaining the functionality of filtering related cases.
=> fix(ai): use subquery instead of from_self

src/dispatch/signal/service.py
This PR fixes a potential transaction issue by removing a redundant commit in the create_signal_instance function, since commit behavior is already managed by the nested context manager.
[This context manager](https://github.com/Netflix/dispatch/blob/main/src/dispatch/plugins/dispatch_aws/plugin.py#L112-L116) calls `create_signal_instance`
```
for message in response["Messages"]:
...
with db_session.begin_nested():
signal_instance = signal_service.create_signal_instance(
db_session=db_session,
signal_instance_in=signal_instance_in,
)
```
but at the end of [that function](https://github.com/Netflix/dispatch/blob/main/src/dispatch/signal/service.py#L196) we commit the transaction
```
def create_signal_instance(*, db_session: Session, signal_instance_in: SignalInstanceCreate):
... …
```
=> fix(signal): remove redundant `db_session.commit()` in `create_signal_instance`

src/dispatch/plugins/dispatch_slack/incident/interactive.py
This PR fixes the Slack integration for incident updates by ensuring that tag IDs are provided as strings in the interactive message options.
=> fix(slack): values must be str type

src/dispatch/database/service.py
In our current implementation, we encountered an error when attempting to join models within our query construction logic. The error message indicated: 
```plaintext
Mapped instance expected for relationship comparison to object. Classes, queries and other SQL elements are not accepted in this context; for comparison with a subquery, use Case.assignee.has(**criteria).
```
This issue arose because our logic was attempting to track joined models using `InstrumentedAttribute` objects, which led to incorrect comparisons based on object identity rather than logical identity.
**Changes Made:**
1. **Tracking Models Directly:**
- Modified the logic to track the actual model or table objects instead of `InstrumentedAttribute` objects. This is done by using the `parent` attribute when available, …
=> fix(db): fixes joined model comparison error

data/dispatch-sample-data.dump, tests/static/e2e/fixtures/dispatch-fixtures.ts, tests/static/e2e/pages/report-event-page.ts, tests/static/e2e/report-event.spec.ts, tests/static/e2e/routes.ts
Adds end-to-end tests for the security event reporting flow in the Dispatch application’s UI.
- Introduces a new ReportEvent route entry.
- Implements Playwright tests covering standard and urgent event submissions.
- Adds a ReportEventPage page object and updates fixtures to include it.
=> tests(ui): test security event form submission

src/dispatch/case/flows.py, src/dispatch/email_templates/enums.py, src/dispatch/incident/messaging.py, src/dispatch/static/dispatch/src/email_templates/NewEditSheet.vue, tests/factories.py
This PR separates case-specific welcome emails from incident ones by introducing a new `case_welcome` template type and updating all related code paths, UI, and tests.
- Added a new `case_welcome` enum and renamed the old welcome to `incident_welcome`
- Updated factories, messaging, and case flows to use the new template names
- Extended the Vue form to let users choose between incident and case welcome emails
=> fix(cases): use separate email template for cases

src/dispatch/static/dispatch/src/signal/InstanceEntityPopover.vue, src/dispatch/static/dispatch/src/signal/TableInstance.vue
Adds entity information and signal definition filter counts to the signal triggers page. This can then be extended into views that provide signal counts grouped by either entity or snooze filter. 
The entity count column is clickable to reveal the associated entities in the instance.
=> (refactor) signal triggers page with entity information 

src/dispatch/case/flows.py, src/dispatch/case/messaging.py, src/dispatch/conversation/enums.py, src/dispatch/plugins/dispatch_slack/case/enums.py, src/dispatch/plugins/dispatch_slack/case/interactive.py, src/dispatch/plugins/dispatch_slack/fields.py, src/dispatch/plugins/dispatch_slack/plugin.py
This pull request includes adding functionality to prompt assignees to update security events and adds a "visibility" field for case updates in Slack.
* Added `send_event_update_prompt_reminder` to `case_new_create_flow` in `src/dispatch/case/flows.py` and in `src/dispatch/case/messaging.py` to remind assignees to update security event details during triage, which sends an ephemeral Slack message to the assignee with a button to update case details.
* Added a new `escalate_case` command to `ConversationCommands` in `src/dispatch/conversation/enums.py` and mapped it to Slack configurations. [[1]](diffhunk://#diff-0b22c4658daba0172305b641f45a570e4b8380bab60073dac357fcab245338d9R13) [[2]](diffhunk://#diff-84bac68ba28c626f61114b432a7c5b163f03541682e3efeb6d0dddc250a7caa8R415)
* Added …
=> enhancement(events): prompt assignee for triage in Slack

src/dispatch/database/service.py
This PR refines the `apply_filter_specific_joins` mapping by removing several unused case-related entries to fix case filtering behavior.
- Removed redundant `CaseType`, `CaseSeverity`, `CasePriority` mappings to `Project`
- Dropped explicit `Case` joins for `IndividualContact`, `Assignee`, and `Project`
- Kept only necessary entity-to-project relations for cleanup
=> fix(case): fixing case filtering

src/dispatch/auth/permissions.py, src/dispatch/case/service.py, src/dispatch/case/views.py, src/dispatch/document/service.py, src/dispatch/event/flows.py, src/dispatch/event/models.py, src/dispatch/event/service.py, src/dispatch/plugins/dispatch_slack/incident/interactive.py, src/dispatch/static/dispatch/src/case/CaseTimelineTabV1.vue, src/dispatch/static/dispatch/src/case/DeleteEventDialog.vue, src/dispatch/static/dispatch/src/case/EditEventDialog.vue, src/dispatch/static/dispatch/src/case/TimelineExportDialog.vue, src/dispatch/static/dispatch/src/case/TimelineFilterDialog.vue, src/dispatch/static/dispatch/src/case/api.js, src/dispatch/static/dispatch/src/case/store.js, tests/case/test_case_event_views.py, tests/case/test_case_service.py
This PR adds comprehensive timeline management functionality for cases and extends the ability to use the Slack timeline reaction for marking posts to save on the timeline to cases.
1. Added Case Timeline Edit Functionality
- Brought case timeline editing capabilities on par with incident timeline
- Users can now edit existing timeline events (description, time, etc.)
- Added ability to pin/unpin timeline events for better organization
- Timeline events can be deleted when no longer needed
2. Added Slack Post to Timeline Feature to Cases
- Users can now mark Slack posts from cases as timeline events directly from Slack
- Events are properly attributed to the Slack user who created them
- Source field shows "Slack message from {name}" for proper attribution
3. Timeline Export Dialog
- Like …
=> feat(case): adds ability to create and edit custom timeline events for cases

src/dispatch/ai/service.py
This PR updates the tag recommendation flow to disallow recommendations for restricted incidents. Key changes include:
- Raising a `ValueError` when the incident is not found.
- Returning an error message when the incident is restricted.
=> fix(tags): disallow tag recommendations for restricted incidents

requirements-base.txt, src/dispatch/email_templates/views.py
This PR restricts email template creation to users with the appropriate admin permission and updates the Jinja2 dependency.
- Enforce `SensitiveProjectActionPermission` on the `create_email_template` endpoint
- Bump Jinja2 from 3.1.5 to 3.1.6
=> fix(email_templates): disallow creation for non admins

src/dispatch/static/dispatch/src/case/ClosedDialog.vue, src/dispatch/static/dispatch/src/case/DetailsTab.vue
This PR updates the tooltip activator templates by renaming the destructured binding from "props" to "tooltipProps" to ensure unique naming for tooltip properties.
- Renames the tooltip property in DetailsTab.vue
- Applies the same renaming in ClosedDialog.vue
=> fix(ui): tooltip props get unique name

src/dispatch/case/flows.py
This PR updates the case creation flow to add the case assignee and reporter as members to the tactical group.
=> fix(case): add assignee and reporter to case group

src/dispatch/plugins/dispatch_slack/incident/interactive.py
Bolt rejects empty strings passed to input text elements, which can cause the tactical report modal view to fail in the absence of a prior report to fetch. To avoid this error, pass `None` as a parameter in the absence of a prior report instead of an empty string.
=> (bugfix) allow empty tactical report in slack modal

src/dispatch/case/models.py, src/dispatch/incident/models.py, src/dispatch/static/dispatch/src/case/CaseStatus.vue, src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue, src/dispatch/static/dispatch/src/case/Table.vue, src/dispatch/static/dispatch/src/case/TableExportDialog.vue, src/dispatch/static/dispatch/src/incident/IncidentSummaryTable.vue, src/dispatch/static/dispatch/src/incident/Table.vue, src/dispatch/static/dispatch/src/incident/TableExportDialog.vue, src/dispatch/static/dispatch/src/incident/status/IncidentStatus.vue, src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue, src/dispatch/static/dispatch/src/signal/Table.vue, src/dispatch/static/dispatch/src/task/TableExportDialog.vue
This PR adds an incident icon to the status column in the case table and a case icon to status column in the incident able when a case is escalated to an incident.
=> feat(ui): Adds icons for case and incident in table status column

src/dispatch/static/dispatch/src/case/EditSheet.vue, src/dispatch/static/dispatch/src/incident/EditSheet.vue, src/dispatch/static/dispatch/src/router/config.js
This pull request focuses on improving the handling of tabs and navigation in the `EditSheet.vue` components for cases and incidents, as well as adding a new route for case timelines. The key changes include replacing the `key` attribute with `value` for tabs and window items, updating tab navigation logic, and introducing a dedicated route for case timelines.
=> fix EditSheet for cases and incidents to allow linking to Timeline

src/dispatch/plugins/dispatch_slack/case/interactive.py
This pull request refactors the `handle_escalation_submission_event` function in `src/dispatch/plugins/dispatch_slack/case/interactive.py` to improve code clarity by renaming imported functions and using the correct one for `priority`.
=> fix(case): escalation priority not persisting

src/dispatch/database/revisions/tenant/versions/2025-08-06_f2bce475e71b.py, src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
This pull request updates how the "Suggest Security Event over Incident" feature is presented and configured. The main change is to the default value for this feature in the database, and a refactor of the UI alert in the incident report submission form for clarity and better placement.
=> fix(incident): submission form formatting changes

src/dispatch/conversation/flows.py, src/dispatch/messaging/strings.py, src/dispatch/plugins/dispatch_slack/messaging.py, src/dispatch/plugins/dispatch_slack/service.py, tests/ai/test_ai_service.py
Use actual emojis instead of Slack's version of emojis, so emails has proper emojis. This PR also separates out `title` and `text` for better formatting.
=> Add emojis directly and refactor email and Slack messages
